
import {GET as getFinalBoard} from "@/app/api/final-board/live/route";
import {getIntegrations,type SleeperLeagueIntegration} from "@/lib/integrations";
import {ensureTursoSchema} from "@/lib/turso";
import {MOCK_POSITIONS,type MockCandidate,type MockNeed,type MockPosition,type MockTeam,type MockTendency} from "@/lib/mock-draft";

export const dynamic="force-dynamic";

const norm=(value:any)=>String(value??"").trim().toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]/g,"");
const num=(value:any)=>{const n=Number(value);return Number.isFinite(n)?n:null};
const text=(value:any)=>String(value??"").trim();

async function sleeperJson(url:string){
  const res=await fetch(url,{cache:"no-store",headers:{accept:"application/json"}});
  if(!res.ok)throw new Error("Sleeper API returned "+res.status);
  return res.json();
}

function ownerName(user:any){return text(user?.metadata?.team_name)||text(user?.display_name)||text(user?.username)||text(user?.user_id)||"Unknown"}
function matchedIdentity(user:any,roster:any,identity:string){const wanted=identity.trim().toLowerCase();if(!wanted)return false;const values=[roster?.roster_id,roster?.owner_id,user?.user_id,user?.display_name,user?.username,user?.metadata?.team_name].map(x=>String(x??"").trim().toLowerCase()).filter(Boolean);return values.includes(wanted)}
function pickDraft(drafts:any[],draftClass:number){const sorted=[...drafts].sort((a,b)=>{const seasonDelta=Number(b?.season||0)-Number(a?.season||0);if(seasonDelta)return seasonDelta;return Number(b?.start_time||b?.created||0)-Number(a?.start_time||a?.created||0)});return sorted.find(d=>Number(d?.season)===draftClass&&String(d?.status||"").toLowerCase()!=="complete")||sorted.find(d=>Number(d?.season)===draftClass)||sorted.find(d=>String(d?.status||"").toLowerCase()!=="complete")||sorted[0]||null}
function currentOwner(originalRosterId:number,round:number,traded:any[],season:number){const matches=traded.filter((p:any)=>Number(p?.roster_id)===originalRosterId&&Number(p?.round)===round&&(!season||!p?.season||Number(p.season)===season));const latest=matches[matches.length-1];return Number(latest?.owner_id||originalRosterId)}
function slotForPick(pickNo:number,teams:number,type:string){const round=Math.floor((pickNo-1)/teams)+1,within=((pickNo-1)%teams)+1;return String(type||"").toLowerCase()==="snake"&&round%2===0?teams-within+1:within}
function valueScore(player:any){const rank=Number(player?.search_rank||999),age=Number(player?.age),rankScore=rank>0?1/(1+rank/70):0.04,ageFactor=Number.isFinite(age)?Math.max(.72,1-Math.max(0,age-27)*.035):1;return rankScore*ageFactor}
function expectedAtPosition(rosterPositions:any[],position:MockPosition,superflex:boolean){const upper=(Array.isArray(rosterPositions)?rosterPositions:[]).map(x=>String(x).toUpperCase()),direct=upper.filter(x=>x===position).length;if(position==="QB"&&superflex)return Math.max(2,direct);if(position==="RB")return Math.max(2,direct);if(position==="WR")return Math.max(3,direct);return Math.max(1,direct)}
function rawPositionStrength(players:any[],position:MockPosition,expected:number){const atPos=players.filter(p=>String(p?.position||"").toUpperCase()===position).sort((a,b)=>valueScore(b)-valueScore(a)),core=atPos.slice(0,expected).reduce((sum,p)=>sum+valueScore(p),0),depth=atPos.slice(expected,expected+3).reduce((sum,p)=>sum+valueScore(p)*.22,0),missing=Math.max(0,expected-atPos.length);return {raw:Math.max(0,core+depth-missing*.22),depth:atPos.length}}
function needLabel(need:number):MockNeed["label"]{if(need>=.72)return "Priority";if(need>=.52)return "Need";if(need>=.34)return "Depth";return "Strength"}
function buildTeams(league:any,rosters:any[],users:any[],playerDb:any,identity:string){
  const userById=new Map(users.map((u:any)=>[String(u.user_id),u]));
  const superflex=(Array.isArray(league?.roster_positions)?league.roster_positions:[]).some((x:any)=>String(x).toUpperCase()==="SUPER_FLEX");
  const raw=rosters.map((r:any)=>{const user=userById.get(String(r.owner_id)),ids=[...new Set([...(r.players||[]),...(r.reserve||[]),...(r.taxi||[])].map(String))],players=ids.map(id=>playerDb?.[id]).filter(Boolean),byPos={} as Record<MockPosition,{raw:number;depth:number}>;for(const pos of MOCK_POSITIONS)byPos[pos]=rawPositionStrength(players,pos,expectedAtPosition(league?.roster_positions,pos,superflex));return {rosterId:Number(r.roster_id),ownerId:String(r.owner_id||""),ownerKey:norm(ownerName(user)),name:ownerName(user),isMine:matchedIdentity(user,r,identity),byPos}});
  const posRanges={} as Record<MockPosition,{min:number;max:number}>;for(const pos of MOCK_POSITIONS){const values=raw.map(t=>t.byPos[pos].raw);posRanges[pos]={min:Math.min(...values),max:Math.max(...values)}}
  return raw.map(t=>{const needs={} as Record<MockPosition,MockNeed>;for(const pos of MOCK_POSITIONS){const range=posRanges[pos],spread=Math.max(.001,range.max-range.min),strength=(t.byPos[pos].raw-range.min)/spread,need=1-strength;needs[pos]={position:pos,strength,need,label:needLabel(need),depth:t.byPos[pos].depth}}return {rosterId:t.rosterId,ownerId:t.ownerId,ownerKey:t.ownerKey,name:t.name,isMine:t.isMine,needs} satisfies MockTeam})
}
async function ensureMockHistorySchema(){const c=await ensureTursoSchema();await c.execute(`create table if not exists mock_draft_history(id integer primary key autoincrement,league_key text not null,season integer,owner_name text not null,owner_key text not null,pick_no integer,round integer,slot integer,player_name text not null,position text not null,board_rank real,source_label text,fingerprint text not null unique,imported_at text default current_timestamp)`);await c.execute(`create index if not exists mock_draft_history_league_owner_idx on mock_draft_history(league_key,owner_key,season)`);return c}
async function tendenciesFor(leagueKey:string):Promise<{tendencies:MockTendency[];summary:{samples:number;managers:number;trained:boolean}}>{const c=await ensureMockHistorySchema(),result=await c.execute({sql:"select owner_name,owner_key,pick_no,position,board_rank from mock_draft_history where league_key=? order by season,pick_no,id",args:[leagueKey]}),groups=new Map<string,{ownerName:string;sampleSize:number;positionCounts:Record<MockPosition,number>;rankDelta:number[]}>();for(const row of result.rows){const pos=String(row.position||"").toUpperCase() as MockPosition;if(!MOCK_POSITIONS.includes(pos))continue;const key=String(row.owner_key||"");if(!groups.has(key))groups.set(key,{ownerName:String(row.owner_name||key),sampleSize:0,positionCounts:{QB:0,RB:0,WR:0,TE:0},rankDelta:[]});const g=groups.get(key)!;g.sampleSize++;g.positionCounts[pos]++;const pickNo=num(row.pick_no),boardRank=num(row.board_rank);if(pickNo!=null&&boardRank!=null)g.rankDelta.push(pickNo-boardRank)}const tendencies=[...groups.entries()].map(([ownerKey,g])=>{const share={QB:0,RB:0,WR:0,TE:0} as Record<MockPosition,number>;for(const pos of MOCK_POSITIONS)share[pos]=g.sampleSize?g.positionCounts[pos]/g.sampleSize:0;return {ownerKey,ownerName:g.ownerName,sampleSize:g.sampleSize,avgRankDelta:g.rankDelta.length?g.rankDelta.reduce((a,b)=>a+b,0)/g.rankDelta.length:null,positionShare:share}}),samples=tendencies.reduce((sum,t)=>sum+t.sampleSize,0);return {tendencies,summary:{samples,managers:tendencies.length,trained:samples>=8}}}
async function boardFor(league:SleeperLeagueIntegration,draftClass:number){const request=new Request(`http://internal/api/final-board/live?view=${encodeURIComponent("league:"+league.key)}&draftClass=${encodeURIComponent(String(draftClass))}`),response=await getFinalBoard(request),body=await response.json();if(!response.ok)throw new Error(body?.error||"Could not load league draft board");const rows=Array.isArray(body?.rows)?body.rows:[];return rows.filter((r:any)=>MOCK_POSITIONS.includes(String(r.position||"").toUpperCase() as MockPosition)).filter((r:any)=>Number(r.overallRank)>0).map((r:any)=>({id:String(r.id),name:text(r.name),position:String(r.position).toUpperCase() as MockPosition,college:text(r.college),rank:Number(r.overallRank),positionRank:num(r.positionRank),tier:num(r.tier),grade:num(r.boardGrade),headshotUrl:r.headshot_url?String(r.headshot_url):null} satisfies MockCandidate)).sort((a:any,b:any)=>a.rank-b.rank)}
async function leagueRoom(league:SleeperLeagueIntegration,draftClass:number){
  const root=`https://api.sleeper.app/v1/league/${league.leagueId}`;
  const [leagueData,drafts,traded,rosters,users,playerDb,board,history]=await Promise.all([sleeperJson(root),sleeperJson(root+"/drafts"),sleeperJson(root+"/traded_picks").catch(()=>[]),sleeperJson(root+"/rosters"),sleeperJson(root+"/users"),sleeperJson("https://api.sleeper.app/v1/players/nfl"),boardFor(league,draftClass),tendenciesFor(league.key)]);
  const draft=pickDraft(drafts,draftClass),teamsCount=Number(leagueData?.total_rosters||rosters.length||0),superflex=(Array.isArray(leagueData?.roster_positions)?leagueData.roster_positions:[]).some((x:any)=>String(x).toUpperCase()==="SUPER_FLEX"),teamViews=buildTeams(leagueData,rosters,users,playerDb,String(league.teamIdentity||""));
  if(!draft)return {league:{key:league.key,name:league.name,leagueId:league.leagueId,teams:teamsCount,rounds:0,draftId:null,draftStatus:"No draft configured",draftClass,superflex,tePremium:Boolean(league.tePremium)},slots:[],teams:teamViews,candidates:board,tendencies:history.tendencies,historySummary:history.summary};
  const rounds=Number(draft?.settings?.rounds||4),total=teamsCount*rounds,rawPicks=await sleeperJson(`https://api.sleeper.app/v1/draft/${draft.draft_id}/picks`).catch(()=>[]),selectedByNo=new Map<number,any>(rawPicks.map((p:any)=>[Number(p.pick_no),p])),teamByRoster=new Map(teamViews.map(t=>[t.rosterId,t])),season=Number(draft?.season||leagueData?.season||draftClass);
  const slots=Array.from({length:total},(_,index)=>{const pickNo=index+1,round=Math.floor(index/teamsCount)+1,slot=slotForPick(pickNo,teamsCount,draft.type),originalRosterId=Number(draft?.slot_to_roster_id?.[slot]||slot),rosterId=currentOwner(originalRosterId,round,traded,season),selected=selectedByNo.get(pickNo),team=teamByRoster.get(rosterId);return {pickNo,round,slot,rosterId,team:team?.name||`Roster ${rosterId}`,isMine:Boolean(team?.isMine),livePlayerId:selected?.player_id?String(selected.player_id):null,livePlayer:selected?.metadata?`${selected.metadata.first_name||""} ${selected.metadata.last_name||""}`.trim():null,livePosition:selected?.metadata?.position?String(selected.metadata.position):null}});
  return {league:{key:league.key,name:String(leagueData?.name||league.name),leagueId:league.leagueId,teams:teamsCount,rounds,draftId:String(draft.draft_id),draftStatus:String(draft.status||"pre_draft"),draftClass:Number(draft.season||draftClass),superflex,tePremium:Boolean(league.tePremium)},slots,teams:teamViews,candidates:board,tendencies:history.tendencies,historySummary:history.summary}
}
function aliasValue(row:any,aliases:string[]){for(const [key,value] of Object.entries(row||{}))if(aliases.includes(norm(key))&&text(value))return value;return null}
function canonicalHistoryRow(raw:any,leagueKey:string){const owner=text(raw.ownerName??raw.owner??aliasValue(raw,["owner","ownername","manager","managername","drafter","team","teamname"])),player=text(raw.playerName??raw.player??aliasValue(raw,["player","playername","selection","rookie","prospect"])),position=text(raw.position??raw.pos??aliasValue(raw,["position","pos"])).toUpperCase();if(!owner||!player||!MOCK_POSITIONS.includes(position as MockPosition))return null;const season=num(raw.season??raw.year??aliasValue(raw,["season","year","draftyear","draftclass"])),pickNo=num(raw.pickNo??raw.pick??aliasValue(raw,["pick","pickno","picknumber","overallpick","overall"])),round=num(raw.round??aliasValue(raw,["round","rnd"])),slot=num(raw.slot??aliasValue(raw,["slot","draftslot"])),boardRank=num(raw.boardRank??raw.rank??raw.adp??aliasValue(raw,["boardrank","rank","predraftrank","adp","overallrank"])),ownerKey=norm(owner),fingerprint=[leagueKey,season??"",ownerKey,pickNo??"",norm(player),position].join("|");return {season,owner,ownerKey,pickNo,round,slot,player,position,boardRank,fingerprint}}
export async function GET(req:Request){try{const url=new URL(req.url),leagueKey=url.searchParams.get("leagueKey"),draftClass=Number(url.searchParams.get("draftClass")||2027),config=await getIntegrations(),leagues=config.sleeper.leagues.filter(l=>l.enabled!==false);if(!leagueKey)return Response.json({leagues:leagues.map(l=>({key:l.key,name:l.name,tePremium:Boolean(l.tePremium)}))});const league=leagues.find(l=>l.key===leagueKey);if(!league)return Response.json({error:"League not found"},{status:404});return Response.json(await leagueRoom(league,draftClass))}catch(e:unknown){return Response.json({error:e instanceof Error?e.message:"Could not load mock draft room"},{status:500})}}
export async function POST(req:Request){try{const body=await req.json();if(body?.action!=="import-history")return Response.json({error:"Unsupported action"},{status:400});const leagueKey=text(body.leagueKey),sourceLabel=text(body.sourceLabel)||"Historical import";if(!leagueKey)return Response.json({error:"leagueKey is required"},{status:400});const config=await getIntegrations();if(!config.sleeper.leagues.some(l=>l.key===leagueKey))return Response.json({error:"League not found"},{status:404});const incoming=Array.isArray(body.rows)?body.rows.slice(0,8000):[],rows=incoming.map((r:any)=>canonicalHistoryRow(r,leagueKey)).filter(Boolean) as NonNullable<ReturnType<typeof canonicalHistoryRow>>[];if(!rows.length)return Response.json({error:"No usable historical draft rows were found. Include owner, player and position columns."},{status:400});const c=await ensureMockHistorySchema(),now=new Date().toISOString();for(let i=0;i<rows.length;i+=75)await c.batch(rows.slice(i,i+75).map(row=>({sql:`insert into mock_draft_history(league_key,season,owner_name,owner_key,pick_no,round,slot,player_name,position,board_rank,source_label,fingerprint,imported_at) values(?,?,?,?,?,?,?,?,?,?,?,?,?) on conflict(fingerprint) do update set owner_name=excluded.owner_name,round=excluded.round,slot=excluded.slot,board_rank=excluded.board_rank,source_label=excluded.source_label,imported_at=excluded.imported_at`,args:[leagueKey,row.season,row.owner,row.ownerKey,row.pickNo,row.round,row.slot,row.player,row.position,row.boardRank,sourceLabel,row.fingerprint,now]})),"write");const history=await tendenciesFor(leagueKey);return Response.json({ok:true,imported:rows.length,...history.summary,tendencies:history.tendencies})}catch(e:unknown){return Response.json({error:e instanceof Error?e.message:"Could not import mock draft history"},{status:500})}}
