"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
type Pos="QB"|"RB"|"WR"|"TE";type Player={id:string|number,name:string,position:Pos,college?:string,draft_class:number,scouting_status:string};
const KEY="rookie-draft.players.v1",POSITIONS:Pos[]=["QB","RB","WR","TE"];
function localRows():Player[]{try{return JSON.parse(localStorage.getItem(KEY)||"[]")}catch{return []}}function saveLocal(rows:Player[]){localStorage.setItem(KEY,JSON.stringify(rows))}
export default function Page(){const [rows,setRows]=useState<Player[]>([]),[storage,setStorage]=useState<"loading"|"cloud"|"local">("loading"),[q,setQ]=useState(""),[onlyUnscouted,setOnlyUnscouted]=useState(false),[name,setName]=useState(""),[college,setCollege]=useState(""),[position,setPosition]=useState<Pos>("QB"),[busy,setBusy]=useState(false);
useEffect(()=>{(async()=>{try{const r=await fetch("/api/players",{cache:"no-store"});if(!r.ok)throw 0;setRows(await r.json());setStorage("cloud")}catch{setRows(localRows());setStorage("local")}})()},[]);
const visible=useMemo(()=>rows.filter(x=>x.draft_class===2027&&(!onlyUnscouted||x.scouting_status==="TO_SCOUT")&&(`${x.name} ${x.college||""}`.toLowerCase().includes(q.toLowerCase()))),[rows,q,onlyUnscouted]);
async function add(e:FormEvent){e.preventDefault();if(!name.trim())return;setBusy(true);const draft={id:`local-${Date.now()}`,name:name.trim(),position,college:college.trim(),draft_class:2027,scouting_status:"TO_SCOUT"} as Player;try{if(storage==="cloud"){const r=await fetch("/api/players",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:draft.name,position,college:draft.college,draftClass:2027})});if(!r.ok)throw 0;const made=await r.json();setRows(v=>[...v.filter(x=>!(x.name===made.name&&x.draft_class===made.draft_class)),made])}else{const next=[...rows.filter(x=>!(x.name.toLowerCase()===draft.name.toLowerCase()&&x.draft_class===2027)),draft];setRows(next);saveLocal(next)}setName("");setCollege("")}finally{setBusy(false)}}
async function change(p:Player,status:string,draftClass=2027){const next=rows.map(x=>x.id===p.id?{...x,scouting_status:status,draft_class:draftClass}:x);setRows(next);if(storage==="local")saveLocal(next);else try{const r=await fetch("/api/players",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:p.id,status,draftClass})});if(!r.ok)throw 0}catch{setStorage("local");saveLocal(next)}}
return <><div className="page-head"><div><div className="ey">Discovery layer</div><h1>Players to Scout</h1><p className="muted">The positional-column workflow from V10, now backed by the synced player store.</p></div><span className={`status ${storage}`}>{storage==="cloud"?"● Cloud synced":storage==="local"?"● This device only":"Connecting…"}</span></div>
{storage==="local"&&<div className="notice">Cloud storage is temporarily unavailable. Changes remain on this device until the connection returns.</div>}
<div className="card"><form className="add-grid" onSubmit={add}><input value={name} onChange={e=>setName(e.target.value)} placeholder="Player name"/><select value={position} onChange={e=>setPosition(e.target.value as Pos)}>{POSITIONS.map(x=><option key={x}>{x}</option>)}</select><input value={college} onChange={e=>setCollege(e.target.value)} placeholder="College"/><button disabled={busy}>{busy?"Adding…":"Add to 2027"}</button></form></div>
<div className="toolbar"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search player or college…"/><button className={onlyUnscouted?"success":"ghost"} onClick={()=>setOnlyUnscouted(v=>!v)}>Unscouted only</button></div>
<div className="columns">{POSITIONS.map(pos=>{const list=visible.filter(x=>x.position===pos).sort((a,b)=>a.name.localeCompare(b.name));return <div className="col" key={pos}><h3>{pos}<span>{list.length}</span></h3><div className="list">{list.map(p=><div className="pros" key={p.id}><div className="name">{p.name}</div><div className="school">{p.college||"College not set"} · {p.scouting_status==="FINISHED"?"Scouted":"To scout"}</div><div className="pros-actions">{p.scouting_status!=="FINISHED"&&<button className="small success" onClick={()=>change(p,"FINISHED")}>Finished</button>}<button className="small ghost" onClick={()=>change(p,"TO_SCOUT",2028)}>Return → 2028</button></div></div>)}{!list.length&&<div className="empty">No {pos}s in this view.</div>}</div></div>})}</div>
<div className="notice"><b>Workflow:</b> Finished Scouting removes a prospect from the unscouted queue without deleting the player record. Returning moves the canonical player to the 2028 class.</div></>}