"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
type Player={id:string|number,name:string,position:"QB"|"RB"|"WR"|"TE",college?:string,draft_class:number,scouting_status:string};
const KEY="rookie-draft.players.v1";
function localRows():Player[]{try{return JSON.parse(localStorage.getItem(KEY)||"[]")}catch{return []}}
function saveLocal(rows:Player[]){localStorage.setItem(KEY,JSON.stringify(rows))}
export default function Page(){
 const [rows,setRows]=useState<Player[]>([]),[storage,setStorage]=useState<"loading"|"cloud"|"local">("loading"),[q,setQ]=useState(""),[pos,setPos]=useState("ALL"),[name,setName]=useState(""),[college,setCollege]=useState(""),[position,setPosition]=useState<Player["position"]>("QB"),[busy,setBusy]=useState(false);
 useEffect(()=>{(async()=>{try{const r=await fetch("/api/players",{cache:"no-store"});if(!r.ok)throw 0;const data=await r.json();setRows(data);setStorage("cloud")}catch{setRows(localRows());setStorage("local")}})()},[]);
 const visible=useMemo(()=>rows.filter(x=>x.draft_class===2027&&x.scouting_status==="TO_SCOUT"&&(pos==="ALL"||x.position===pos)&&(`${x.name} ${x.college||""}`.toLowerCase().includes(q.toLowerCase()))).sort((a,b)=>a.position.localeCompare(b.position)||a.name.localeCompare(b.name)),[rows,q,pos]);
 async function add(e:FormEvent){e.preventDefault();if(!name.trim())return;setBusy(true);const draft={id:`local-${Date.now()}`,name:name.trim(),position,college:college.trim(),draft_class:2027,scouting_status:"TO_SCOUT"} as Player;try{if(storage==="cloud"){const r=await fetch("/api/players",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:draft.name,position,college:draft.college,draftClass:2027})});if(!r.ok)throw 0;const made=await r.json();setRows(v=>[...v.filter(x=>!(x.name===made.name&&x.draft_class===made.draft_class)),made])}else{const next=[...rows.filter(x=>!(x.name.toLowerCase()===draft.name.toLowerCase()&&x.draft_class===2027)),draft];setRows(next);saveLocal(next)}setName("");setCollege("")}finally{setBusy(false)}}
 async function change(p:Player,status:string,draftClass=2027){const next=rows.map(x=>x.id===p.id?{...x,scouting_status:status,draft_class:draftClass}:x);setRows(next);if(storage==="local")saveLocal(next);else{try{const r=await fetch("/api/players",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:p.id,status,draftClass})});if(!r.ok)throw 0}catch{setStorage("local");saveLocal(next)}}}
 const counts=Object.fromEntries(["QB","RB","WR","TE"].map(p=>[p,visible.filter(x=>x.position===p).length]));
 return <><div className="page-head"><div><h1>Players to Scout</h1><p className="muted">2027 draft-eligible players who still need final film evaluation.</p></div><span className={`status ${storage}`}>{storage==="cloud"?"● Cloud synced":storage==="local"?"● This device only":"Connecting…"}</span></div>
 {storage==="local"&&<div className="notice">Cloud storage is not configured yet. Changes are safely retained in this browser for now and the app will switch to cloud storage once the database is connected.</div>}
 <div className="grid compact">{["QB","RB","WR","TE"].map(p=><div className="card stat" key={p}><b>{p}</b><span>{counts[p]||0}</span></div>)}</div>
 <div className="card"><h2>Add prospect</h2><form className="add-grid" onSubmit={add}><input value={name} onChange={e=>setName(e.target.value)} placeholder="Player name"/><select value={position} onChange={e=>setPosition(e.target.value as Player["position"])}>{["QB","RB","WR","TE"].map(x=><option key={x}>{x}</option>)}</select><input value={college} onChange={e=>setCollege(e.target.value)} placeholder="College"/><button disabled={busy}>{busy?"Adding…":"Add to 2027"}</button></form></div>
 <div className="toolbar"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search players or colleges…"/><select value={pos} onChange={e=>setPos(e.target.value)}><option>ALL</option>{["QB","RB","WR","TE"].map(x=><option key={x}>{x}</option>)}</select></div>
 <div className="card scroll"><table><thead><tr><th>Pos</th><th>Player</th><th>College</th><th>Class</th><th>Workflow</th></tr></thead><tbody>{visible.map(r=><tr key={r.id}><td><b>{r.position}</b></td><td className="player-name">{r.name}</td><td>{r.college||"—"}</td><td>{r.draft_class}</td><td><div className="row-actions"><button className="small success" onClick={()=>change(r,"FINISHED")}>Finished Scouting</button><button className="small ghost" onClick={()=>change(r,"TO_SCOUT",2028)}>Returning → 2028</button></div></td></tr>)}</tbody></table>{!visible.length&&<div className="empty"><b>No players in this view.</b><span>Add a prospect above or change your filters.</span></div>}</div></>;
}