"use client";
import {FormEvent,useEffect,useMemo,useState} from "react";
import {schoolStyle} from "@/lib/school-colors";
import PlayerName from "@/components/PlayerName";
type Pos="QB"|"RB"|"WR"|"TE"; type Player={id:string|number,name:string,position:Pos,college?:string,draft_class:number,scouting_status:string,watch_order?:number,jersey_number?:string,headshot_url?:string}; type Media={url?:string,logo?:string,jersey?:string};
const KEY="rookie-draft.players.v1",POSITIONS:Pos[]=["QB","RB","WR","TE"];
function localRows():Player[]{try{return JSON.parse(localStorage.getItem(KEY)||"[]")}catch{return []}}
function saveLocal(rows:Player[]){localStorage.setItem(KEY,JSON.stringify(rows))}
export default function Page(){
 const [rows,setRows]=useState<Player[]>([]),[media,setMedia]=useState<Record<string,Media>>({}),[imageFailed,setImageFailed]=useState<Record<string,boolean>>({}),[storage,setStorage]=useState<"loading"|"cloud"|"local">("loading"),[q,setQ]=useState(""),[name,setName]=useState(""),[college,setCollege]=useState(""),[position,setPosition]=useState<Pos>("QB"),[busy,setBusy]=useState(false),[error,setError]=useState(""),[selected,setSelected]=useState<Player|null>(null);
 async function load(){setError("");try{const r=await fetch("/api/players",{cache:"no-store"});if(!r.ok)throw new Error("Cloud player store returned "+r.status);const data=await r.json();if(!Array.isArray(data))throw new Error("Invalid player response");setRows(data);setStorage("cloud")}catch(e:any){const local=localRows();setRows(local);setStorage("local");setError(e?.message||"Could not load cloud players")}}
 useEffect(()=>{load();const refresh=()=>load();window.addEventListener("rookie-draft:players-changed",refresh);return()=>window.removeEventListener("rookie-draft:players-changed",refresh)},[]);
 useEffect(()=>{const missing=rows.filter(x=>x.draft_class===2027&&!media[String(x.id)]).slice(0,40);if(!missing.length)return;Promise.all(missing.map(async x=>{try{const r=await fetch(`/api/player-headshot?id=${x.id}`);const j=await r.json();return [String(x.id),{url:j.url||x.headshot_url||"",logo:j.logo||"",jersey:j.jersey||x.jersey_number||""}] as const}catch{return [String(x.id),{url:x.headshot_url||"",logo:"",jersey:x.jersey_number||""}] as const}})).then(found=>setMedia(m=>({...m,...Object.fromEntries(found)})))},[rows,media]);
 const active=useMemo(()=>rows.filter(x=>x.draft_class===2027&&x.scouting_status!=="FINISHED"&&((x.name+" "+(x.college||"")).toLowerCase().includes(q.toLowerCase()))),[rows,q]);
 async function add(e:FormEvent){e.preventDefault();if(!name.trim())return;setBusy(true);const draft={id:"local-"+Date.now(),name:name.trim(),position,college:college.trim(),draft_class:2027,scouting_status:"TO_SCOUT"} as Player;try{if(storage==="cloud"){const r=await fetch("/api/players",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:draft.name,position,college:draft.college,draftClass:2027})});const j=await r.json();if(!r.ok)throw new Error(j.error||"Could not add player");setRows(v=>[...v.filter(x=>!(x.name.toLowerCase()===j.name.toLowerCase()&&x.draft_class===j.draft_class)),j])}else{const next=[...rows.filter(x=>!(x.name.toLowerCase()===draft.name.toLowerCase()&&x.draft_class===2027)),draft];setRows(next);saveLocal(next)}setName("");setCollege("")}catch(e:any){setError(e?.message||"Could not add player")}finally{setBusy(false)}}
 async function change(p:Player,patch:any){const next=rows.map(x=>x.id===p.id?{...x,...patch}:x);setRows(next);if(storage==="local"){saveLocal(next);return}try{const r=await fetch("/api/players",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:p.id,...patch,status:patch.scouting_status,draftClass:patch.draft_class,watchOrder:patch.watch_order})});if(!r.ok)throw 0}catch{setStorage("local");saveLocal(next);setError("Cloud update failed; this change is saved only in this browser.")}}
 const groups=[...POSITIONS,"Maybe"] as const;
 return <><div className="page-head"><div><div className="ey">Scouting Tools · Players to Scout</div><h1>Players to Scout</h1><p className="muted">Functional translation of the workbook's QB / RB / WR / TE / Maybe scouting queue.</p></div><span className={"status "+storage}>{storage==="cloud"?"● Cloud synced":storage==="local"?"● This device only":"Connecting…"}</span></div>
 {error&&<div className="notice"><b>Data status:</b> {error} <button className="small ghost" onClick={load}>Retry</button></div>}
 
 <div className="toolbar"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search player or college…"/><span className="muted">{active.length} active 2027 prospects</span></div>
 <div className="columns scout-queue-columns">{POSITIONS.map(group=>{const list=active.filter(x=>x.position===group&&x.scouting_status!=="MAYBE").sort((a,b)=>(a.watch_order||0)-(b.watch_order||0));return <div className={"col scout-col scout-col-"+group.toLowerCase()} key={group}><h3>{group}<span>{list.length}</span></h3><div className="list">{list.map(p=><button className="pros college-card player-card-button scouting-player-card" style={schoolStyle(p.college)} key={p.id} onClick={()=>setSelected(p)}>{(()=>{const m=media[String(p.id)]||{},src=!imageFailed[String(p.id)]&&(m.url||p.headshot_url),teamLogo=m.logo||"";return src?<img className="player-headshot" src={src} alt="" onError={()=>setImageFailed(v=>({...v,[String(p.id)]:true}))}/>:teamLogo?<img className="player-headshot player-college-logo" src={teamLogo} alt="" />:<div className="player-headshot player-headshot-fallback">{p.name.split(" ").map(x=>x[0]).slice(0,2).join("")}</div>})()}<div className="player-card-copy"><PlayerName id={p.id} className="name">{p.name}</PlayerName><div className="college-card-school">{p.college||"College not set"}{(p.jersey_number||media[String(p.id)]?.jersey)?` · #${p.jersey_number||media[String(p.id)]?.jersey}`:""}</div></div></button>)}{!list.length&&<div className="empty">No players in this column.</div>}</div></div>})}</div>{(()=>{const list=active.filter(x=>x.scouting_status==="MAYBE").sort((a,b)=>(a.watch_order||0)-(b.watch_order||0));return <div className="maybe-section"><div className="maybe-section-head"><h3>Maybe</h3><span>{list.length}</span></div><div className="maybe-grid">{list.map(p=><button className="pros college-card player-card-button scouting-player-card" style={schoolStyle(p.college)} key={p.id} onClick={()=>setSelected(p)}>{(()=>{const m=media[String(p.id)]||{},src=!imageFailed[String(p.id)]&&(m.url||p.headshot_url),teamLogo=m.logo||"";return src?<img className="player-headshot" src={src} alt="" onError={()=>setImageFailed(v=>({...v,[String(p.id)]:true}))}/>:teamLogo?<img className="player-headshot player-college-logo" src={teamLogo} alt="" />:<div className="player-headshot player-headshot-fallback">{p.name.split(" ").map(x=>x[0]).slice(0,2).join("")}</div>})()}<div className="player-card-copy"><PlayerName id={p.id} className="name">{p.name}</PlayerName><div className="college-card-school">{p.college||"College not set"}{(p.jersey_number||media[String(p.id)]?.jersey)?` · #${p.jersey_number||media[String(p.id)]?.jersey}`:""}</div></div></button>)}{!list.length&&<div className="empty">No players in Maybe.</div>}</div></div>})()}
 {selected&&<div className="tool-modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setSelected(null)}><div className="tool-modal"><div className="page-head"><div><div className="ey">{selected.position} · 2027</div><h2>{selected.name}</h2><p className="muted">{selected.college}</p></div><button className="small ghost" onClick={()=>setSelected(null)}>Close</button></div><div className="grid compact"><div className="card"><div className="muted">Status</div><b>{selected.scouting_status}</b></div><div className="card"><div className="muted">Position</div><b>{selected.position}</b></div><div className="card"><div className="muted">College</div><b>{selected.college||"—"}</b></div></div>{(selected.scouting_status==="WATCHED"||selected.scouting_status==="FINISHED")&&<a className="button" href={"/scouting?player="+selected.id}>Open Scouting Record</a>}</div></div>}<div className="notice"><b>Parity status:</b> The five-column queue, Maybe movement, watched/finished states, and returning-player transition are now represented as app state. Player workflow actions now belong in the persistent Scouting Tools / GM Tools menus, matching the workbook.</div></>}
