import {cacheGet,cacheSet} from "@/lib/cache";
const norm=(s:string)=>String(s||"").toLowerCase().replace(/&/g,"and").replace(/\b(jr|sr|ii|iii|iv)\b/g,"").replace(/[^a-z0-9]+/g," ").trim().replace(/\s+/g," "),aliases:Record<string,string>={"miami fl":"miami","miami florida":"miami","mizzou":"missouri","uconn":"connecticut","umass":"massachusetts","nc state":"north carolina state","usc":"southern california","ole miss":"mississippi","cal":"california","usf":"south florida","app state":"appalachian state","wku":"western kentucky","byu":"brigham young","smu":"southern methodist","ucf":"central florida","utep":"texas el paso","utsa":"texas san antonio","fiu":"florida international","uab":"alabama birmingham","texas aandm":"texas a m"};
export const collegeKey=(s:string)=>aliases[norm(s)]||norm(s);
export const samePlayerName=(a:string,b:string)=>{const x=norm(a),y=norm(b);return x===y||x.replace(/ /g,"")===y.replace(/ /g,"")};
const KNOWN_ESPN_IDS:Record<string,string>=Object.fromEntries([
["Darian Mensah","5121169"],["Demond Williams Jr.","5079653"],["Connor Weigman","4685574"],["Gunner Stockton","4685578"],["Braxton Woodson","5158343"],
["Mark Fletcher Jr.","4870736"],["Antwan Raymond","5209945"],["Quintrevion Wisner","4871076"],["Gavin Sawchuk","4685545"],["Bryson Washington","4954455"],
["J'Koby Williams","5086393"],["Sutton Smith","4805256"],["Reuben Owens II","4870934"],["Jordan Lyle","5079591"],["Lendon Phillips Jr.","5155048"],
["Arlis Boardingham","4702556"],["DJ Vonnahme","5218931"],["Cole Spence","4799991"],["Elija Lofton","5079503"],["Dylan Wade","4922996"],
["Bryant Wesco","5112674"],["Cooper Barkate","4804878"],["Junior Sherril","5078165"],["Eugene Wilson III","4921154"],["Wyatt Young","5148787"],
["Ryan Wingo","5218633"],["Eric Singleton Jr.","5095360"],["Griffin Wilde","5154734"],["Trent Walker","4879567"]
].map(([name,id])=>[norm(name),id]));
function logoOf(team:any){return team?.logo||team?.logos?.find?.((x:any)=>x?.rel?.includes?.("default"))?.href||team?.logos?.[0]?.href||""}
function collectTeams(x:any,out:any[]=[]){if(!x||typeof x!=="object")return out;if(x.team?.id)out.push(x.team);else if(x.id&&(x.location||x.displayName))out.push(x);if(Array.isArray(x))for(const v of x)collectTeams(v,out);else for(const v of Object.values(x))collectTeams(v,out);return out}
export async function collegeTeams(){const cached=await cacheGet<any[]>("cfb:teams:v2");if(cached?.length)return cached;const r=await fetch("https://site.api.espn.com/apis/site/v2/sports/football/college-football/teams?limit=1000",{next:{revalidate:86400}});if(!r.ok)throw new Error("ESPN teams "+r.status);const raw=collectTeams(await r.json()),seen=new Set<string>(),teams=raw.filter((t:any)=>t?.id&&!seen.has(String(t.id))&&!!seen.add(String(t.id))).map((t:any)=>({id:String(t.id),location:t.location||"",displayName:t.displayName||"",shortDisplayName:t.shortDisplayName||"",name:t.name||"",abbreviation:t.abbreviation||"",logo:logoOf(t)}));await cacheSet("cfb:teams:v2",teams,604800);return teams}
export async function findCollegeTeam(college:string){const k=collegeKey(college),teams=await collegeTeams();return teams.find((t:any)=>[t.location,t.displayName,t.shortDisplayName,t.name,t.abbreviation].filter(Boolean).some((n:string)=>{const x=collegeKey(n);return x===k||x.includes(k)||k.includes(x)}))||null}
function collectAthletes(x:any,out:any[]=[]){if(!x||typeof x!=="object")return out;if((x.id||x.uid)&&(x.fullName||x.displayName||x.name)&&((x.position?.abbreviation)||x.jersey||x.headshot))out.push(x);if(Array.isArray(x))for(const v of x)collectAthletes(v,out);else for(const v of Object.values(x))collectAthletes(v,out);return out}
export async function teamRoster(teamId:string){const key="cfb:roster:"+teamId,cached=await cacheGet<any[]>(key);if(cached?.length)return cached;const r=await fetch(`https://site.api.espn.com/apis/site/v2/sports/football/college-football/teams/${teamId}/roster`,{next:{revalidate:21600}});if(!r.ok)return[];const roster=collectAthletes(await r.json());await cacheSet(key,roster,86400);return roster}
export async function teamSchedule(teamId:string){const key="cfb:team-schedule:2026:"+teamId,cached=await cacheGet<any[]>(key);if(cached)return cached;const r=await fetch(`https://site.api.espn.com/apis/site/v2/sports/football/college-football/teams/${teamId}/schedule?season=2026`,{next:{revalidate:21600}});if(!r.ok)return[];const j=await r.json(),events=Array.isArray(j.events)?j.events:[];await cacheSet(key,events,21600);return events}
export type PlayerMediaResult={espnId:string;url:string;jersey:string|null;logo:string;source:string;reason:string};
function athleteMedia(a:any,source:string,fallbackLogo=""):PlayerMediaResult{const espnId=String(a?.id||a?.uid||"").match(/(?:a:)?(\d+)$/)?.[1]||"",url=String(a?.headshot?.href||a?.headshot||a?.image?.default||(espnId?`https://a.espncdn.com/i/headshots/college-football/players/full/${espnId}.png`:"")),jersey=String(a?.jersey||"").trim()||null,logo=String(logoOf(a?.team)||fallbackLogo||"");return {espnId,url,jersey,logo,source,reason:""}}
async function searchEspnPlayer(name:string,college:string){const u=new URL("https://site.web.api.espn.com/apis/search/v2");u.search=new URLSearchParams({query:name,sport:"football",limit:"10"}).toString();const r=await fetch(u,{next:{revalidate:604800}});if(!r.ok)return null;const j=await r.json(),groups=Array.isArray(j?.items)?j.items:[],contents=groups.filter((g:any)=>g?.type==="player").flatMap((g:any)=>Array.isArray(g.contents)?g.contents:[]),matches=contents.filter((x:any)=>samePlayerName(x.displayName||"",name));if(!matches.length)return null;const preferred=matches.filter((x:any)=>x?.defaultLeagueSlug==="college-football"||x?.description==="NCAAF"||x?.sport==="football"),pool=preferred.length?preferred:matches,ck=collegeKey(college),hit=pool.find((x:any)=>{const sk=collegeKey(x.subtitle||"");return sk===ck||sk.includes(ck)||ck.includes(sk)})||pool[0],espnId=String(hit.uid||"").match(/~a:(\d+)/)?.[1]||String(hit.link?.web||"").match(/\/id\/(\d+)/)?.[1]||"";if(!espnId)return null;try{const d=await fetch(`https://site.web.api.espn.com/apis/common/v3/sports/football/college-football/athletes/${espnId}`,{next:{revalidate:604800}});if(d.ok){const athlete=(await d.json())?.athlete;if(athlete&&samePlayerName(athlete.displayName||athlete.fullName||"",name))return athleteMedia(athlete,"ESPN search",hit.image?.default||"")}}catch{}return athleteMedia({...hit,id:espnId,headshot:{href:hit.image?.default||""}},"ESPN search")}
async function knownEspnPlayer(name:string,logo:string):Promise<PlayerMediaResult|null>{const id=KNOWN_ESPN_IDS[norm(name)];if(!id)return null;try{const r=await fetch(`https://site.web.api.espn.com/apis/common/v3/sports/football/college-football/athletes/${id}`,{next:{revalidate:604800}});if(r.ok){const athlete=(await r.json())?.athlete;if(athlete)return athleteMedia(athlete,"ESPN verified ID",logo)}}catch{}return athleteMedia({id,headshot:{href:`https://a.espncdn.com/i/headshots/college-football/players/full/${id}.png`}},"ESPN verified ID",logo)}
export async function resolvePlayerMedia(name:string,college:string){const team=await findCollegeTeam(college).catch(()=>null),logo=team?.logo||"";if(team){const roster=await teamRoster(team.id),a=roster.find((x:any)=>[x.fullName,x.displayName,x.name,[x.firstName,x.lastName].filter(Boolean).join(" ")].filter(Boolean).some((n:string)=>samePlayerName(n,name)));if(a)return athleteMedia(a,"ESPN roster",logo)}const known=await knownEspnPlayer(name,logo);if(known)return known;const searched=await searchEspnPlayer(name,college);if(searched)return {...searched,logo:searched.logo||logo};return {espnId:"",url:"",jersey:null,logo:String(logo||""),source:"",reason:team?"player-not-found":"team-not-found"} as PlayerMediaResult}

export type PlayerMediaMatch={espnId:string|null,url:string|null,jersey:string|null,source:string,logo:string};
async function athleteDetails(id:string){try{const r=await fetch(`https://site.api.espn.com/apis/site/v2/sports/football/college-football/athletes/${id}`,{next:{revalidate:21600}});return r.ok?await r.json():null}catch{return null}}
function athleteId(x:any){const uid=String(x?.uid||"");const m=uid.match(/~a:(\d+)/);if(m)return m[1];const web=String(x?.link?.web||"");const w=web.match(/\/id\/(\d+)/);return w?.[1]||String(x?.id||"").match(/^\d+$/)?.[0]||""}
export async function searchCollegePlayer(name:string,college:string){try{const u=new URL("https://site.web.api.espn.com/apis/search/v2");u.search=new URLSearchParams({query:name,sport:"football",limit:"10"}).toString();const r=await fetch(u,{cache:"no-store"});if(!r.ok)return null;const j=await r.json(),groups=Array.isArray(j.items)?j.items:[],players=groups.filter((g:any)=>g?.type==="player").flatMap((g:any)=>Array.isArray(g.contents)?g.contents:[]).filter((x:any)=>x?.description==="NCAAF"||x?.defaultLeagueSlug==="college-football"),exact=players.filter((x:any)=>samePlayerName(x.displayName||"",name));if(!exact.length)return null;const ck=collegeKey(college),preferred=exact.find((x:any)=>{const sk=collegeKey(String(x.subtitle||""));return sk===ck||sk.startsWith(ck+" ")||ck.startsWith(sk+" ")}),hit=preferred||exact[0],id=athleteId(hit);if(!id)return null;const detail=await athleteDetails(id),athlete=detail?.athlete||detail,jersey=String(athlete?.jersey||"").trim()||null,url=hit?.image?.default||hit?.image?.defaultDark||athlete?.headshot?.href||`https://a.espncdn.com/i/headshots/college-football/players/full/${id}.png`;return {espnId:id,url,jersey,source:"ESPN search"} }catch{return null}}
export async function resolveCollegePlayerMedia(name:string,college:string):Promise<PlayerMediaMatch>{const team=await findCollegeTeam(college),logo=team?.logo||"";if(team){const roster=await teamRoster(team.id),a=roster.find((x:any)=>[x.fullName,x.displayName,x.name,[x.firstName,x.lastName].filter(Boolean).join(" ")].filter(Boolean).some((n:string)=>samePlayerName(n,name)));if(a){const id=String(a.id||"").replace(/^s:.*?~a:/,""),url=a.headshot?.href||a.headshot||(id?`https://a.espncdn.com/i/headshots/college-football/players/full/${id}.png`:null),jersey=String(a.jersey||"").trim()||null;return {espnId:id||null,url:url||null,jersey,source:"ESPN roster",logo}}}const hit=await searchCollegePlayer(name,college);return hit?{...hit,logo}:{espnId:null,url:null,jersey:null,source:team?"player-not-found":"team-not-found",logo}}
