import {db,ensureSchema} from "@/lib/db";
const ESPN_SCORE="https://site.web.api.espn.com/apis/site/v2/sports/football/college-football/scoreboard";
const ESPN_RANK="https://site.api.espn.com/apis/site/v2/sports/football/college-football/rankings";
const ymd=(d:Date)=>d.toISOString().slice(0,10).replace(/-/g,"");
async function eventsFor(dates:string){const batches=await Promise.all(["80","81"].map(async group=>{const q=new URLSearchParams({limit:"1000",groups:group,seasontype:"2",dates});const r=await fetch(ESPN_SCORE+"?"+q,{cache:"no-store"});if(!r.ok)throw new Error("ESPN schedule "+r.status);return (await r.json()).events||[]}));const seen=new Set<string>();return batches.flat().filter((e:any)=>e?.id&&!seen.has(String(e.id))&&!!seen.add(String(e.id)))}
async function saveEvents(events:any[]){await ensureSchema();const q=db();for(const e of events)await q`INSERT INTO college_football_events(espn_event_id,kickoff,event,updated_at) VALUES(${String(e.id)},${e.date},${JSON.stringify(e)},now()) ON CONFLICT(espn_event_id) DO UPDATE SET kickoff=excluded.kickoff,event=excluded.event,updated_at=now()`}
async function saveRankings(){try{const r=await fetch(ESPN_RANK,{cache:"no-store"});if(!r.ok)return;const j=await r.json();await db()`INSERT INTO settings(key,value,updated_at) VALUES('college-football-rankings',${JSON.stringify(j.rankings||[])},now()) ON CONFLICT(key) DO UPDATE SET value=excluded.value,updated_at=now()`}catch{}}
export async function syncFullSeason(){const events=await eventsFor("2026");await saveEvents(events);await saveRankings();return {events:events.length}}
export function upcomingWeek(){const now=new Date(),parts=new Intl.DateTimeFormat("en-US",{timeZone:"America/New_York",year:"numeric",month:"2-digit",day:"2-digit",weekday:"short"}).formatToParts(now),v=Object.fromEntries(parts.map(x=>[x.type,x.value])),base=new Date(Date.UTC(+v.year,+v.month-1,+v.day,16)),dow=["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].indexOf(v.weekday),toThu=(4-dow+7)%7,start=new Date(base);start.setUTCDate(base.getUTCDate()+toThu);const end=new Date(start);end.setUTCDate(start.getUTCDate()+4);return {start,end}}
export async function syncUpcomingWeek(){const {start,end}=upcomingWeek(),events:any[]=[];for(let d=new Date(start);d<=end;d=new Date(d.getTime()+86400000))events.push(...await eventsFor(ymd(d)));const seen=new Set<string>(),unique=events.filter(e=>!seen.has(String(e.id))&&!!seen.add(String(e.id)));await saveEvents(unique);await saveRankings();return {events:unique.length,start:ymd(start),end:ymd(end)}}
