import {cacheGet,cacheSet} from "@/lib/cache";
const norm=(s:string)=>String(s||"").toLowerCase().replace(/&/g,"and").replace(/\b(jr|sr|ii|iii|iv)\b/g,"").replace(/[^a-z0-9]+/g," ").trim().replace(/\s+/g," "),aliases:Record<string,string>={"miami fl":"miami","miami florida":"miami","mizzou":"missouri","uconn":"connecticut","umass":"massachusetts","nc state":"north carolina state","usc":"southern california","ole miss":"mississippi","cal":"california","usf":"south florida","app state":"appalachian state","wku":"western kentucky","byu":"brigham young","smu":"southern methodist","ucf":"central florida","utep":"texas el paso","utsa":"texas san antonio","fiu":"florida international","uab":"alabama birmingham","texas aandm":"texas a m"};
export const collegeKey=(s:string)=>aliases[norm(s)]||norm(s);
export const samePlayerName=(a:string,b:string)=>{const x=norm(a),y=norm(b);return x===y||x.replace(/ /g,"")===y.replace(/ /g,"")};
function logoOf(team:any){return team?.logo||team?.logos?.find?.((x:any)=>x?.rel?.includes?.("default"))?.href||team?.logos?.[0]?.href||""}
function collectTeams(x:any,out:any[]=[]){if(!x||typeof x!=="object")return out;if(x.team?.id)out.push(x.team);else if(x.id&&(x.location||x.displayName))out.push(x);if(Array.isArray(x))for(const v of x)collectTeams(v,out);else for(const v of Object.values(x))collectTeams(v,out);return out}
export async function collegeTeams(){const cached=await cacheGet<any[]>("cfb:teams:v2");if(cached?.length)return cached;const r=await fetch("https://site.api.espn.com/apis/site/v2/sports/football/college-football/teams?limit=1000",{next:{revalidate:86400}});if(!r.ok)throw new Error("ESPN teams "+r.status);const raw=collectTeams(await r.json()),seen=new Set<string>(),teams=raw.filter((t:any)=>t?.id&&!seen.has(String(t.id))&&!!seen.add(String(t.id))).map((t:any)=>({id:String(t.id),location:t.location||"",displayName:t.displayName||"",shortDisplayName:t.shortDisplayName||"",name:t.name||"",abbreviation:t.abbreviation||"",logo:logoOf(t)}));await cacheSet("cfb:teams:v2",teams,604800);return teams}
export async function findCollegeTeam(college:string){const k=collegeKey(college),teams=await collegeTeams();return teams.find((t:any)=>[t.location,t.displayName,t.shortDisplayName,t.name,t.abbreviation].filter(Boolean).some((n:string)=>{const x=collegeKey(n);return x===k||x.includes(k)||k.includes(x)}))||null}
function collectAthletes(x:any,out:any[]=[]){if(!x||typeof x!=="object")return out;if((x.id||x.uid)&&(x.fullName||x.displayName||x.name)&&((x.position?.abbreviation)||x.jersey||x.headshot))out.push(x);if(Array.isArray(x))for(const v of x)collectAthletes(v,out);else for(const v of Object.values(x))collectAthletes(v,out);return out}
export async function teamRoster(teamId:string){const key="cfb:roster:"+teamId,cached=await cacheGet<any[]>(key);if(cached?.length)return cached;const r=await fetch(`https://site.api.espn.com/apis/site/v2/sports/football/college-football/teams/${teamId}/roster`,{next:{revalidate:21600}});if(!r.ok)return[];const roster=collectAthletes(await r.json());await cacheSet(key,roster,86400);return roster}
export async function teamSchedule(teamId:string){const key="cfb:team-schedule:2026:"+teamId,cached=await cacheGet<any[]>(key);if(cached)return cached;const r=await fetch(`https://site.api.espn.com/apis/site/v2/sports/football/college-football/teams/${teamId}/schedule?season=2026`,{next:{revalidate:21600}});if(!r.ok)return[];const j=await r.json(),events=Array.isArray(j.events)?j.events:[];await cacheSet(key,events,21600);return events}
function athleteMedia(a:any,source:string,fallbackLogo=""){const espnId=String(a?.id||a?.uid||"").match(/(?:a:)?(\d+)$/)?.[1]||"",url=a?.headshot?.href||a?.headshot||a?.image?.default||(espnId?`https://a.espncdn.com/i/headshots/college-football/players/full/${espnId}.png`:""),jersey=String(a?.jersey||"").trim()||null,logo=logoOf(a?.team)||fallbackLogo;return {espnId,url,jersey,logo,source}}
async function searchEspnPlayer(name:string,college:string){const u=new URL("https://site.web.api.espn.com/apis/search/v2");u.search=new URLSearchParams({query:name,sport:"football",limit:"10"}).toString();const r=await fetch(u,{next:{revalidate:604800}});if(!r.ok)return null;const j=await r.json(),groups=Array.isArray(j?.items)?j.items:[],contents=groups.filter((g:any)=>g?.type==="player").flatMap((g:any)=>Array.isArray(g.contents)?g.contents:[]),matches=contents.filter((x:any)=>x?.defaultLeagueSlug==="college-football"&&x?.sport==="football"&&samePlayerName(x.displayName||"",name));if(!matches.length)return null;const ck=collegeKey(college),hit=matches.find((x:any)=>{const sk=collegeKey(x.subtitle||"");return sk===ck||sk.includes(ck)||ck.includes(sk)})||matches[0],espnId=String(hit.uid||"").match(/~a:(\d+)/)?.[1]||String(hit.link?.web||"").match(/\/id\/(\d+)/)?.[1]||"";if(!espnId)return null;try{const d=await fetch(`https://site.web.api.espn.com/apis/common/v3/sports/football/college-football/athletes/${espnId}`,{next:{revalidate:604800}});if(d.ok){const athlete=(await d.json())?.athlete;if(athlete&&samePlayerName(athlete.displayName||athlete.fullName||"",name))return athleteMedia(athlete,"ESPN search",hit.image?.default||"")}}catch{}return athleteMedia({...hit,id:espnId,headshot:{href:hit.image?.default||""}},"ESPN search")}
export async function resolvePlayerMedia(name:string,college:string){const team=await findCollegeTeam(college).catch(()=>null),logo=team?.logo||"";if(team){const roster=await teamRoster(team.id),a=roster.find((x:any)=>[x.fullName,x.displayName,x.name,[x.firstName,x.lastName].filter(Boolean).join(" ")].filter(Boolean).some((n:string)=>samePlayerName(n,name)));if(a)return athleteMedia(a,"ESPN roster",logo)}const searched=await searchEspnPlayer(name,college);if(searched)return {...searched,logo:searched.logo||logo};return {espnId:"",url:"",jersey:null,logo,source:"",reason:team?"player-not-found":"team-not-found"}}
