import {cacheSet} from "@/lib/cache";
const ESPN_SCORE="https://site.web.api.espn.com/apis/site/v2/sports/football/college-football/scoreboard";
const ESPN_RANK="https://site.api.espn.com/apis/site/v2/sports/football/college-football/rankings";
export const ymd=(d:Date)=>d.toISOString().slice(0,10).replace(/-/g,"");
export function currentFootballWeek(){const now=new Date(),parts=new Intl.DateTimeFormat("en-US",{timeZone:"America/New_York",year:"numeric",month:"2-digit",day:"2-digit",weekday:"short"}).formatToParts(now),v=Object.fromEntries(parts.map(x=>[x.type,x.value])),base=new Date(Date.UTC(+v.year,+v.month-1,+v.day,16)),dow=["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].indexOf(v.weekday),back=(dow+3)%7,start=new Date(base);start.setUTCDate(base.getUTCDate()-back);const end=new Date(start);end.setUTCDate(start.getUTCDate()+4);return {start,end}}
export function nextFootballWeek(){const w=currentFootballWeek(),start=new Date(w.start);start.setUTCDate(start.getUTCDate()+7);const end=new Date(start);end.setUTCDate(start.getUTCDate()+4);return {start,end}}
async function eventsForDay(day:string){const batches=await Promise.all(["80","81"].map(async group=>{const q=new URLSearchParams({limit:"500",groups:group,seasontype:"2",dates:day});const r=await fetch(ESPN_SCORE+"?"+q,{cache:"no-store"});if(!r.ok)throw new Error("ESPN schedule "+r.status+" on "+day);return (await r.json()).events||[]}));const seen=new Set<string>();return batches.flat().filter((e:any)=>e?.id&&!seen.has(String(e.id))&&!!seen.add(String(e.id)))}
export async function saveRankings(){try{const r=await fetch(ESPN_RANK,{cache:"no-store"});if(!r.ok)return[];const rankings=(await r.json()).rankings||[];await cacheSet("cfb:rankings",rankings,86400);return rankings}catch{return[]}}
export async function syncRange(start:Date,end:Date){const events:any[]=[];for(let d=new Date(start);d<=end;d=new Date(d.getTime()+86400000))events.push(...await eventsForDay(ymd(d)));const seen=new Set<string>(),unique=events.filter(e=>!seen.has(String(e.id))&&!!seen.add(String(e.id)));await cacheSet(`cfb:schedule:${ymd(start)}:${ymd(end)}`,unique,604800);return unique}
export async function syncFullSeason(){let total=0;for(let start=new Date(Date.UTC(2026,7,27,16));start<=new Date(Date.UTC(2026,11,17,16));start=new Date(start.getTime()+7*86400000)){const end=new Date(start);end.setUTCDate(start.getUTCDate()+4);total+=(await syncRange(start,end)).length}await saveRankings();return {events:total}}
export async function syncUpcomingWeek(){const {start,end}=nextFootballWeek(),events=await syncRange(start,end);await saveRankings();return {events:events.length,start:ymd(start),end:ymd(end)}}
