import {cacheGet,cacheSet} from "@/lib/cache";
const norm=(s:string)=>String(s||"").toLowerCase().replace(/&/g,"and").replace(/\b(jr|sr|ii|iii|iv)\b/g,"").replace(/[^a-z0-9]+/g," ").trim().replace(/\s+/g," "),aliases:Record<string,string>={"miami fl":"miami florida","mizzou":"missouri","uconn":"connecticut","umass":"massachusetts","nc state":"north carolina state","usc":"southern california","ole miss":"mississippi","cal":"california","usf":"south florida","app state":"appalachian state","wku":"western kentucky","byu":"brigham young","smu":"southern methodist","ucf":"central florida","utep":"texas el paso","utsa":"texas san antonio","fiu":"florida international","uab":"alabama birmingham","texas aandm":"texas a m"};
export const collegeKey=(s:string)=>aliases[norm(s)]||norm(s);export const samePlayerName=(a:string,b:string)=>{const x=norm(a),y=norm(b);return x===y||x.replace(/ /g,"")===y.replace(/ /g,"")};
function collectTeams(x:any,out:any[]=[]){if(!x||typeof x!=="object")return out;if(x.team?.id)out.push(x.team);else if(x.id&&(x.location||x.displayName))out.push(x);if(Array.isArray(x))for(const v of x)collectTeams(v,out);else for(const v of Object.values(x))collectTeams(v,out);return out}
export async function collegeTeams(){const cached=await cacheGet<any[]>("cfb:teams:v1");if(cached?.length)return cached;const r=await fetch("https://site.api.espn.com/apis/site/v2/sports/football/college-football/teams?limit=1000",{next:{revalidate:86400}});if(!r.ok)throw new Error("ESPN teams "+r.status);const raw=collectTeams(await r.json()),seen=new Set<string>(),teams=raw.filter((t:any)=>t?.id&&!seen.has(String(t.id))&&!!seen.add(String(t.id))).map((t:any)=>({id:String(t.id),location:t.location||"",displayName:t.displayName||"",shortDisplayName:t.shortDisplayName||"",name:t.name||"",abbreviation:t.abbreviation||"",logo:t.logo||t.logos?.[0]?.href||""}));await cacheSet("cfb:teams:v1",teams,604800);return teams}
export async function findCollegeTeam(college:string){const k=collegeKey(college),teams=await collegeTeams();return teams.find((t:any)=>[t.location,t.displayName,t.shortDisplayName,t.name,t.abbreviation].filter(Boolean).some((n:string)=>collegeKey(n)===k))||null}
function collectAthletes(x:any,out:any[]=[]){if(!x||typeof x!=="object")return out;if((x.id||x.uid)&&(x.fullName||x.displayName||x.name)&&((x.position?.abbreviation)||x.jersey||x.headshot))out.push(x);if(Array.isArray(x))for(const v of x)collectAthletes(v,out);else for(const v of Object.values(x))collectAthletes(v,out);return out}
export async function teamRoster(teamId:string){const key="cfb:roster:"+teamId,cached=await cacheGet<any[]>(key);if(cached?.length)return cached;const r=await fetch(`https://site.api.espn.com/apis/site/v2/sports/football/college-football/teams/${teamId}/roster`,{next:{revalidate:21600}});if(!r.ok)return[];const roster=collectAthletes(await r.json());await cacheSet(key,roster,86400);return roster}
export async function teamSchedule(teamId:string){const key="cfb:team-schedule:2026:"+teamId,cached=await cacheGet<any[]>(key);if(cached)return cached;const r=await fetch(`https://site.api.espn.com/apis/site/v2/sports/football/college-football/teams/${teamId}/schedule?season=2026`,{next:{revalidate:21600}});if(!r.ok)return[];const j=await r.json(),events=Array.isArray(j.events)?j.events:[];await cacheSet(key,events,21600);return events}
