const RANKS:Record<string,string>={
  "Josh Hoover": "QB1",
  "Aidan Chiles": "QB2",
  "Lincoln Kienholz": "QB3",
  "Kevin Jennings": "QB4",
  "Trinidad Chambliss": "QB5",
  "Sam Leavitt": "QB6",
  "Arch Manning": "QB7",
  "Julian Sayin": "QB8",
  "CJ Carr": "QB9",
  "Colton Joseph": "QB10",
  "Turbo Richard": "RB1",
  "Gavin Sawchuk": "RB2",
  "Keyjuan Brown": "RB3",
  "Isaac Brown": "RB4",
  "Joshua Dye": "RB5",
  "Kewan Lacy": "RB6",
  "Dilin Jones": "RB7",
  "Hollywood Smothers": "RB8",
  "Abu Sama III": "RB9",
  "Raleek Brown": "RB10",
  "Nick Marsh": "WR1",
  "Charlie Becker": "WR2",
  "Griffin Wilde": "WR3",
  "Tre Richardson": "WR4",
  "Yamir Knight": "WR5",
  "Deuce Alexander": "WR6",
  "Darrell Gill Jr.": "WR7",
  "Johntay Cook II": "WR8",
  "Jackson Harris": "WR9",
  "Jayce Brown": "WR10",
  "Eugene Wilson III": "WR11",
  "Jeremiah Smith": "WR12",
  "Cam Coleman": "WR13",
  "Jordan Faison": "WR14",
  "Emmett Mosley V": "WR15",
  "Ryan Wingo": "WR16",
  "Brandon Inniss": "WR17",
  "Devin McCuin": "WR18",
  "Jaden Greathouse": "WR19",
  "Alex Honig": "TE1",
  "Jaleel Skinner": "TE2",
  "Brody Foley": "TE3",
  "Theo Melin Ohrstrom": "TE4",
  "Luke Hasz": "TE5",
  "Trey'Dez Green": "TE6",
  "Michael Masunas": "TE7"
};
const key=(s:string)=>String(s||"").toLowerCase().replace(/[^a-z0-9]+/g," ").trim().replace(/\s+/g," ");
const INDEX:Record<string,string>=Object.fromEntries(Object.entries(RANKS).map(([name,rank])=>[key(name),rank]));
export function finalBoardPositionRank(name:string,position:string){return INDEX[key(name)]||position}
export const finalBoardRanksUpdatedAt="2026-09-26";
