import { db } from "@/lib/db";

const WATCHLIST:{name:string;position:"QB"|"RB"|"WR"|"TE";college:string}[]=[
{position:"QB",name:"Arch Manning",college:"Texas"},
{position:"QB",name:"Dante Moore",college:"Oregon"},
{position:"QB",name:"Drew Mestemaker",college:"Oklahoma State"},
{position:"QB",name:"CJ Carr",college:"Notre Dame"},
{position:"QB",name:"Julian Sayin",college:"Ohio State"},
{position:"QB",name:"Trinidad Chambliss",college:"Ole Miss"},
{position:"QB",name:"Darian Mensah",college:"Miami (FL)"},
{position:"QB",name:"CJ Bailey",college:"NC State"},
{position:"QB",name:"Jayden Maiava",college:"USC"},
{position:"QB",name:"Drake Lindsey",college:"Minnesota"},
{position:"QB",name:"Demond Williams Jr.",college:"Washington"},
{position:"QB",name:"LaNorris Sellers",college:"South Carolina"},
{position:"QB",name:"Sam Leavitt",college:"LSU"},
{position:"QB",name:"John Mateer",college:"Oklahoma"},
{position:"QB",name:"Josh Hoover",college:"Indiana"},
{position:"QB",name:"Rocco Becht",college:"Penn State"},
{position:"QB",name:"Byrum Brown",college:"Auburn"},
{position:"QB",name:"Marcel Reed",college:"Texas A&M"},
{position:"QB",name:"Nico Iamaleava",college:"UCLA"},
{position:"QB",name:"Kevin Jennings",college:"SMU"},
{position:"QB",name:"Avery Johnson",college:"Kansas State"},
{position:"QB",name:"Jackson Arnold",college:"UNLV"},
{position:"QB",name:"Devon Dampier",college:"Utah"},
{position:"QB",name:"Connor Weigman",college:"Houston"},
{position:"QB",name:"DJ Lagway",college:"Baylor"},
{position:"QB",name:"Noah Fifita",college:"Arizona"},
{position:"QB",name:"Gunner Stockton",college:"Georgia"},
{position:"QB",name:"Walker Eget",college:"Duke"},
{position:"QB",name:"Michael Hawkins Jr.",college:"West Virginia"},
{position:"QB",name:"Austin Simmons",college:"Mizzou"},
{position:"QB",name:"Alonza Barnett III",college:"UCF"},
{position:"QB",name:"Eli Holstein",college:"Virginia"},
{position:"QB",name:"Cutter Boley",college:"Arizona State"},
{position:"QB",name:"Jaden Craig",college:"TCU"},
{position:"QB",name:"Steve Angeli",college:"Syracuse"},
{position:"QB",name:"Beau Pribula",college:"Virginia"},
{position:"QB",name:"Aidan Chiles",college:"Northwestern"},
{position:"QB",name:"Malachi Nelson",college:"Syracuse"},
{position:"QB",name:"Colton Joseph",college:"Wisconsin"},
{position:"QB",name:"Lincoln Kienholz",college:"Louisville"},
{position:"QB",name:"JC French IV",college:"Cincinnati"},
{position:"QB",name:"Katin Houser",college:"Illinois"},
{position:"QB",name:"NIck Minicucci",college:"Delaware"},
{position:"QB",name:"Kenny Minchey",college:"Kentucky"},
{position:"QB",name:"Chase Mason",college:"South Dakota State"},
{position:"QB",name:"Ty Pennington",college:"Northern Arizona"},
{position:"QB",name:"Beau Brungard",college:"Youngstown State"},
{position:"QB",name:"Jaylen Raynor",college:"Iowa State"},
{position:"QB",name:"Owen McCown",college:"UTSA"},
{position:"QB",name:"Braxton Woodson",college:"Navy"},
{position:"QB",name:"Dylan Raiola",college:"Oregon"},
{position:"QB",name:"Jordan Cooke",college:"Idaho State"},
{position:"QB",name:"Nathan Hayes",college:"North Dakota State"},
{position:"QB",name:"Marcus Stokes",college:"Memphis"},
{position:"QB",name:"Ashton Daniels",college:"Florida State"},
{position:"RB",name:"Ahmad Hardy",college:"Mizzou"},
{position:"RB",name:"Jadan Baugh",college:"Florida"},
{position:"RB",name:"Kewan Lacy",college:"Ole Miss"},
{position:"RB",name:"Mark Fletcher Jr.",college:"Miami (FL)"},
{position:"RB",name:"LJ Martin",college:"BYU"},
{position:"RB",name:"Nate Frazier",college:"Georgia"},
{position:"RB",name:"Hollywood Smothers",college:"Texas"},
{position:"RB",name:"Darius Taylor",college:"Minnesota"},
{position:"RB",name:"Isaac Brown",college:"Louisville"},
{position:"RB",name:"Raleek Brown",college:"Texas"},
{position:"RB",name:"Antwan Raymond",college:"Rutgers"},
{position:"RB",name:"Jamal Roberts",college:"Mizzou"},
{position:"RB",name:"Quinten Joyner",college:"Texas Tech"},
{position:"RB",name:"Waymond Jordan",college:"USC"},
{position:"RB",name:"CJ Baxter",college:"Kentucky"},
{position:"RB",name:"Makhi Hughes",college:"Houston"},
{position:"RB",name:"Jahiem White",college:"North Texas"},
{position:"RB",name:"Quintrevion Wisner",college:"Florida State"},
{position:"RB",name:"Dallan Hayden",college:"Memphis"},
{position:"RB",name:"Jovantae Barnes",college:"Kentucky"},
{position:"RB",name:"Dylan Edwards",college:"Kansas"},
{position:"RB",name:"Gavin Sawchuk",college:"Northwestern"},
{position:"RB",name:"Mel Brown",college:"Colorado State"},
{position:"RB",name:"CJ Campbell Jr.",college:"Duke"},
{position:"RB",name:"Bryson Washington",college:"Auburn"},
{position:"RB",name:"Justice Haynes",college:"Georgia Tech"},
{position:"RB",name:"Dante Dowdell",college:"Georgia"},
{position:"RB",name:"Marcellous Hawkins",college:"Virginia Tech"},
{position:"RB",name:"A'Marion Peterson",college:"UTSA"},
{position:"RB",name:"J'Koby Williams",college:"Texas Tech"},
{position:"RB",name:"DeSean Bishop",college:"Tennessee"},
{position:"RB",name:"Fluff Bothwell",college:"Mississippi State"},
{position:"RB",name:"Wayshawn Parker",college:"Utah"},
{position:"RB",name:"Joe Jackson",college:"Kansas State"},
{position:"RB",name:"Jordan Marshall",college:"Michigan"},
{position:"RB",name:"King Miller",college:"USC"},
{position:"RB",name:"Carson Hansen",college:"Penn State"},
{position:"RB",name:"Abu Sama III",college:"Wisconsin"},
{position:"RB",name:"Wayne Knight",college:"UCLA"},
{position:"RB",name:"Jeremiah Cobb",college:"Auburn"},
{position:"RB",name:"Cam Cook",college:"West Virginia"},
{position:"RB",name:"Malachi Hosley",college:"Georgia Tech"},
{position:"RB",name:"Jalen Buckley",college:"Western Michigan"},
{position:"RB",name:"Eli Gillman",college:"Montana"},
{position:"RB",name:"Victor Dawson",college:"Illinois State"},
{position:"RB",name:"Marquis Gillis",college:"Arizona State"},
{position:"RB",name:"Sutton Smith",college:"Arkansas"},
{position:"RB",name:"Cam Edwards",college:"Michigan State"},
{position:"RB",name:"Kenji Christian",college:"UConn"},
{position:"RB",name:"Charles Pierre Jr.",college:"South Dakota"},
{position:"RB",name:"Rayshon Luke",college:"Fresno State"},
{position:"RB",name:"Turbo Richard",college:"Indiana"},
{position:"RB",name:"Jayden Scott",college:"NC State"},
{position:"RB",name:"Daniel Hill",college:"Alabama"},
{position:"RB",name:"Trequan Jones",college:"Tulsa"},
{position:"RB",name:"Lucky Sutton",college:"San Diego State"},
{position:"RB",name:"Reuben Owens II",college:"Texas A&M"},
{position:"RB",name:"Sedrick Alexander",college:"Vanderbilt"},
{position:"RB",name:"Dilin Jones",college:"LSU"},
{position:"RB",name:"Jordan Lyle",college:"Miami (FL)"},
{position:"RB",name:"Lendon Phillips Jr.",college:"Iowa"},
{position:"RB",name:"Jeremy Payne",college:"TCU"},
{position:"RB",name:"Dwight Phillips Jr.",college:"Georgia"},
{position:"RB",name:"James Peoples",college:"Penn State"},
{position:"RB",name:"Joshua Dye",college:"Ole Miss"},
{position:"RB",name:"Evan Pryor",college:"Florida"},
{position:"RB",name:"Kanye Udoh",college:"Liberty"},
{position:"RB",name:"Keyjuan Brown",college:"Louisville"},
{position:"WR",name:"Jeremiah Smith",college:"Ohio State"},
{position:"WR",name:"Cam Coleman",college:"Texas"},
{position:"WR",name:"KJ Duff",college:"Rutgers"},
{position:"WR",name:"Mario Craver",college:"Texas A&M"},
{position:"WR",name:"Charlie Becker",college:"Indiana"},
{position:"WR",name:"Nick Marsh",college:"Indiana"},
{position:"WR",name:"Bryant Wesco",college:"Clemson"},
{position:"WR",name:"Cooper Barkate",college:"Miami (FL)"},
{position:"WR",name:"TJ Moore",college:"Clemson"},
{position:"WR",name:"Omarion Miller",college:"Arizona State"},
{position:"WR",name:"Ryan Coleman-Williams",college:"Alabama"},
{position:"WR",name:"Junior Sherril",college:"Vanderbilt"},
{position:"WR",name:"Amare Thomas",college:"Houston"},
{position:"WR",name:"Reed Harris",college:"Arizona State"},
{position:"WR",name:"Jaden Greathouse",college:"Notre Dame"},
{position:"WR",name:"Duce Robinson",college:"Florida State"},
{position:"WR",name:"Eugene Wilson III",college:"LSU"},
{position:"WR",name:"Wyatt Young",college:"Oklahoma State"},
{position:"WR",name:"Ryan Wingo",college:"Texas"},
{position:"WR",name:"Nyck Harbor",college:"South Carolina"},
{position:"WR",name:"Jayce Brown",college:"LSU"},
{position:"WR",name:"Ian Strong",college:"California"},
{position:"WR",name:"Johntay Cook II",college:"Ole Miss"},
{position:"WR",name:"Darrell Gill Jr.",college:"Ole Miss"},
{position:"WR",name:"DeAndre Moore Jr",college:"Colorado"},
{position:"WR",name:"Trell Harris",college:"Oklahoma"},
{position:"WR",name:"Isaiah Horton",college:"Texas A&M"},
{position:"WR",name:"Brandon Inniss",college:"Ohio State"},
{position:"WR",name:"Jordan Dwyer",college:"TCU"},
{position:"WR",name:"Jordan Mosley",college:"Colorado State"},
{position:"WR",name:"Nic Anderson",college:"Kentucky"},
{position:"WR",name:"Evan Stewart",college:"Oregon"},
{position:"WR",name:"Hykeem Williams",college:"Colorado"},
{position:"WR",name:"Cayden Lee",college:"Mizzou"},
{position:"WR",name:"Eric Singleton Jr.",college:"Florida"},
{position:"WR",name:"Beau Sparks",college:"Texas State"},
{position:"WR",name:"Jordan Faison",college:"Notre Dame"},
{position:"WR",name:"Mike Matthews",college:"Tennessee"},
{position:"WR",name:"Braylon Staley",college:"Tennessee"},
{position:"WR",name:"Griffin Wilde",college:"Northwestern"},
{position:"WR",name:"Keshaun Singleton",college:"Auburn"},
{position:"WR",name:"Devin McCuin",college:"Ohio State"},
{position:"WR",name:"London Humphreys",college:"Georgia"},
{position:"WR",name:"Isaiah Sategna III",college:"Oklahoma"},
{position:"WR",name:"Tre Richardson",college:"Louisville"},
{position:"WR",name:"Chase Hendricks",college:"California"},
{position:"WR",name:"Chris Marshall",college:"Arkansas"},
{position:"WR",name:"Anthony Evans III",college:"Mississippi State"},
{position:"WR",name:"Chase Sowell",college:"Penn State"},
{position:"WR",name:"DJ Black",college:"South Carolina"},
{position:"WR",name:"Micahi Danzy",college:"Florida State"},
{position:"WR",name:"Brett Eskildsen",college:"Penn State"},
{position:"WR",name:"Deuce Alexander",college:"Ole Miss"},
{position:"WR",name:"Justin Bowick",college:"Oklahoma State"},
{position:"WR",name:"Yamir Knight",college:"SMU"},
{position:"WR",name:"Cameron Seldon",college:"South Florida"},
{position:"WR",name:"Baron Tipton",college:"North Texas"},
{position:"WR",name:"Tony Diaz",college:"Iowa"},
{position:"WR",name:"Noah Rogers",college:"Alabama"},
{position:"WR",name:"Josiah Freeman",college:"Fresno State"},
{position:"WR",name:"Hudson Clement",college:"Illinois"},
{position:"WR",name:"Nyziah Hunter",college:"Nebraska"},
{position:"WR",name:"Kenny Johnson",college:"Texas Tech"},
{position:"WR",name:"Iverson Hooks",college:"Oregon"},
{position:"WR",name:"Trent Walker",college:"Houston"},
{position:"WR",name:"Emmett Mosley V",college:"Texas"},
{position:"WR",name:"Micah Hudson",college:"Texas Tech"},
{position:"WR",name:"Chance Robinson",college:"NC State"},
{position:"WR",name:"Jared Richardson",college:"Duke"},
{position:"WR",name:"Marquis Johnson",college:"Mississippi State"},
{position:"WR",name:"Nico Brown",college:"Stanford"},
{position:"WR",name:"Jackson Harris",college:"LSU"},
{position:"WR",name:"Jeremiah McClellan",college:"Oregon"},
{position:"WR",name:"Louis Brown IV",college:"Baylor"},
{position:"WR",name:"Que'Sean Brown",college:"Virginia Tech"},
{position:"WR",name:"Collin Dixon",college:"Illiinois"},
{position:"TE",name:"Trey'Dez Green",college:"LSU"},
{position:"TE",name:"Jamari Johnson",college:"Oregon"},
{position:"TE",name:"Alex Honig",college:"Northwestern"},
{position:"TE",name:"Jeremiah Hasley",college:"Duke"},
{position:"TE",name:"Garrett Oakley",college:"Kansas State"},
{position:"TE",name:"Benjamin Brahmer",college:"Penn State"},
{position:"TE",name:"Arlis Boardingham",college:"Bowling Green"},
{position:"TE",name:"Trey Leckner",college:"Washington State"},
{position:"TE",name:"Terrance Carter Jr.",college:"Texas Tech"},
{position:"TE",name:"Luke Hasz",college:"Ole Miss"},
{position:"TE",name:"Lawson Luckie",college:"Georgia"},
{position:"TE",name:"DJ Vonnahme",college:"Iowa"},
{position:"TE",name:"Kaden Feagin",college:"Illinois"},
{position:"TE",name:"Peter Clarke",college:"Temple"},
{position:"TE",name:"Chris Corbo",college:"Georgia Tech"},
{position:"TE",name:"Luke Reynolds",college:"Virginia Tech"},
{position:"TE",name:"Theo Melin Ohrstrom",college:"SMU"},
{position:"TE",name:"Jaden Platt",college:"Arkansas"},
{position:"TE",name:"Brett Norfleet",college:"Mizzou"},
{position:"TE",name:"Davin Stoffel",college:"Illinois"},
{position:"TE",name:"Gabe Burkle",college:"Penn State"},
{position:"TE",name:"Reis Kessel",college:"North Dakota State"},
{position:"TE",name:"Walker Lyons",college:"BYU"},
{position:"TE",name:"Hayden Hansen",college:"Oklahoma"},
{position:"TE",name:"Kari Ashley",college:"TCU"},
{position:"TE",name:"Andrew Rappleyea",college:"Penn State"},
{position:"TE",name:"Brody Foley",college:"Louisville"},
{position:"TE",name:"Michael Masunas",college:"Texas"},
{position:"TE",name:"Eli Finley",college:"Louisiana Tech"},
{position:"TE",name:"Cole Spence",college:"Vanderbilt"},
{position:"TE",name:"Luke Lindenmeyer",college:"Nebraska"},
{position:"TE",name:"Christian Abney",college:"Illinois"},
{position:"TE",name:"Rocky Beers",college:"Oklahoma"},
{position:"TE",name:"Addison Ostrenga",college:"Iowa"},
{position:"TE",name:"Keyan Burnett",college:"UNLV"},
{position:"TE",name:"Ethan Davis",college:"Tennessee"},
{position:"TE",name:"Willie Rodriguez",college:"Kentucky"},
{position:"TE",name:"Decker DeGraaf",college:"Washington"},
{position:"TE",name:"Elija Lofton",college:"Miami (FL)"},
{position:"TE",name:"Kylan Fox",college:"Purdue"},
{position:"TE",name:"Dorian Thomas",college:"California"},
{position:"TE",name:"Jaleel Skinner",college:"Louisville"},
{position:"TE",name:"Jake Johnson",college:"Auburn"},
{position:"TE",name:"Jaden Reddell",college:"Georgia"},
{position:"TE",name:"Dylan Wade",college:"UCF"}
];

export async function seedV10Watchlist(){
 const q=db();
 const [done]=await q`select value from settings where key='seed_v10_watchlist_2027'`;
 if(done)return false;
 const payload=JSON.stringify(WATCHLIST);
 await q`insert into players(name,position,college,draft_class,scouting_status)
 select x.name,x.position,x.college,2027,'TO_SCOUT' from jsonb_to_recordset(${payload}::jsonb) as x(name text,position text,college text)
 on conflict(name,draft_class) do update set position=excluded.position,college=excluded.college,updated_at=now()`;
 await q`insert into settings(key,value) values('seed_v10_watchlist_2027',${JSON.stringify({source:"V10 read-only snapshot",count:WATCHLIST.length})}::jsonb) on conflict(key) do nothing`;
 return true;
}
