"use client";
import {useEffect,useMemo,useState} from "react";
type Player={id:string|number,name:string,position:"QB"|"RB"|"WR"|"TE",college?:string,draft_class:number,scouting_status?:string};
const PLAYER_KEY="rookie-draft.players.v1";
const ORDER_KEY="rookie-draft.final-board-order.v1";
function read<T>(key:string,fallback:T):T{try{return JSON.parse(localStorage.getItem(key)||"") as T}catch{return fallback}}
export default function Page(){const [rows,setRows]=useState<Player[]>([]),[storage,setStorage]=useState<"loading"|"cloud"|"local">("loading"),[order,setOrder]=useState<string[]>([]),[pos,setPos]=useState("ALL"),[q,setQ]=useState("");
useEffect(()=>{setOrder(read<string[]>(ORDER_KEY,[]));(async()=>{try{const r=await fetch("/api/players",{cache:"no-store"});if(!r.ok)throw 0;setRows(await r.json());setStorage("cloud")}catch{setRows(read<Player[]>(PLAYER_KEY,[]));setStorage("local")}})()},[]);
const eligible=useMemo(()=>rows.filter(x=>x.draft_class===2027&&x.scouting_status==="FINISHED"),[rows]);
const ranked=useMemo(()=>{const key=(p:Player)=>String(p.id);return [...eligible].sort((a,b)=>{const ai=order.indexOf(key(a)),bi=order.indexOf(key(b));if(ai<0&&bi<0)return a.position.localeCompare(b.position)||a.name.localeCompare(b.name);if(ai<0)return 1;if(bi<0)return-1;return ai-bi})},[eligible,order]);
const visible=ranked.filter(x=>(pos==="ALL"||x.position===pos)&&(`${x.name} ${x.college||""}`.toLowerCase().includes(q.toLowerCase())));
function move(p:Player,delta:number){const ids=ranked.map(x=>String(x.id)),id=String(p.id),i=ids.indexOf(id),j=Math.max(0,Math.min(ids.length-1,i+delta));if(i===j)return;ids.splice(i,1);ids.splice(j,0,id);setOrder(ids);localStorage.setItem(ORDER_KEY,JSON.stringify(ids))}
return <><div className="page-head"><div><h1>Final Draft Board</h1><p className="muted">2027 players marked Finished Scouting. Manual ordering is available now; authoritative grade-based ordering stays locked until exact workbook grade parity is migrated.</p></div><span className={`status ${storage}`}>{storage==="cloud"?"● Cloud player pool":storage==="local"?"● Device player pool":"Connecting…"}</span></div>
<div className="notice">Board order is currently a manual, device-local planning aid—not a replacement for your established Final Grade formula. No scouting math has been approximated.</div>
<div className="toolbar"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search board…"/><select value={pos} onChange={e=>setPos(e.target.value)}><option>ALL</option>{["QB","RB","WR","TE"].map(x=><option key={x}>{x}</option>)}</select></div>
<div className="card scroll"><table><thead><tr><th>#</th><th>Pos</th><th>Player</th><th>College</th><th>Authoritative Grade</th><th>Order</th></tr></thead><tbody>{visible.map(r=><tr key={r.id}><td>{ranked.findIndex(x=>x.id===r.id)+1}</td><td><b>{r.position}</b></td><td className="player-name">{r.name}</td><td>{r.college||"—"}</td><td><span className="muted">Pending parity</span></td><td><div className="row-actions"><button className="small ghost" onClick={()=>move(r,-1)} aria-label={`Move ${r.name} up`}>↑</button><button className="small ghost" onClick={()=>move(r,1)} aria-label={`Move ${r.name} down`}>↓</button></div></td></tr>)}</tbody></table>{!visible.length&&<div className="empty"><b>No finished 2027 players yet.</b><span>Mark prospects Finished Scouting from Players to Scout and they will appear here.</span></div>}</div></>}
