"use client";
import {useEffect,useMemo,useState} from "react";
import {schoolStyle} from "@/lib/school-colors";
type Player={id:string|number,name:string,position:"QB"|"RB"|"WR"|"TE",college?:string,draft_class:number,scouting_status?:string};
const PLAYER_KEY="rookie-draft.players.v1",ORDER_KEY="rookie-draft.final-board-order.v1",TIER_KEY="rookie-draft.final-board-tiers.v1";const LEAGUES=["Base","One League","D+R","Last Man Standing","Last Minute"];
function read<T>(key:string,fallback:T):T{try{return JSON.parse(localStorage.getItem(key)||"") as T}catch{return fallback}}
export default function Page(){const [rows,setRows]=useState<Player[]>([]),[storage,setStorage]=useState<"loading"|"cloud"|"local">("loading"),[order,setOrder]=useState<string[]>([]),[tiers,setTiers]=useState<Record<string,string>>({}),[pos,setPos]=useState("ALL"),[q,setQ]=useState(""),[league,setLeague]=useState("Base"),[grades,setGrades]=useState<Record<string,{pre:number|null,final:number|null}>>({});
useEffect(()=>{setOrder(read<string[]>(ORDER_KEY,[]));setTiers(read<Record<string,string>>(TIER_KEY,{}));(async()=>{try{const r=await fetch("/api/players",{cache:"no-store"});if(!r.ok)throw 0;setRows(await r.json());setStorage("cloud");fetch("/api/grades?draftClass=2027",{cache:"no-store"}).then(r=>r.json()).then(g=>Array.isArray(g)&&setGrades(Object.fromEntries(g.map((x:any)=>[String(x.id),{pre:x.preDraftGrade,final:x.finalGrade}])))).catch(()=>{})}catch{setRows(read<Player[]>(PLAYER_KEY,[]));setStorage("local")}})()},[]);
const eligible=useMemo(()=>rows.filter(x=>x.draft_class===2027&&(x.scouting_status==="WATCHED"||x.scouting_status==="FINISHED")),[rows]);
const ranked=useMemo(()=>{const key=(p:Player)=>String(p.id);return [...eligible].sort((a,b)=>{const ai=order.indexOf(key(a)),bi=order.indexOf(key(b));if(ai<0&&bi<0)return a.position.localeCompare(b.position)||a.name.localeCompare(b.name);if(ai<0)return 1;if(bi<0)return-1;return ai-bi})},[eligible,order]);
const visible=ranked.filter(x=>(pos==="ALL"||x.position===pos)&&(`${x.name} ${x.college||""}`.toLowerCase().includes(q.toLowerCase())));
function persistOrder(ids:string[]){setOrder(ids);localStorage.setItem(ORDER_KEY,JSON.stringify(ids))}function move(p:Player,delta:number){const ids=ranked.map(x=>String(x.id)),id=String(p.id),i=ids.indexOf(id),j=Math.max(0,Math.min(ids.length-1,i+delta));if(i===j)return;ids.splice(i,1);ids.splice(j,0,id);persistOrder(ids)}
function setTier(id:string,tier:string){const next={...tiers,[id]:tier};if(!tier)delete next[id];setTiers(next);localStorage.setItem(TIER_KEY,JSON.stringify(next))}
function resetOrder(){if(!confirm("Reset manual board order? Tier labels will be kept."))return;persistOrder([])}
function exportBoard(){const payload={version:1,exportedAt:new Date().toISOString(),draftClass:2027,order,tiers};const blob=new Blob([JSON.stringify(payload,null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`rookie-draft-2027-board-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)}
return <><div className="page-head"><div><h1>Final Draft Board</h1><p className="muted">All watched 2027 players from Scouting. Manual ordering and planning tiers are available now; the Authoritative Grade column now uses the workbook-derived Pre-Draft Grade for players whose scouting inputs are complete.</p></div><span className={`status ${storage}`}>{storage==="cloud"?"● Cloud player pool":storage==="local"?"● Device player pool":"Connecting…"}</span></div>
<div className="notice">Order and tiers remain planning aids. Authoritative Grade uses the workbook-derived Final Grade whenever Team Score and Draft Capital inputs exist, otherwise it falls back to the workbook-derived Pre-Draft Grade.</div>
<div className="tabs">{LEAGUES.map(x=><button key={x} className={x===league?"success":"ghost"} onClick={()=>setLeague(x)}>{x}</button>)}</div><div className="toolbar"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search board…"/><select value={pos} onChange={e=>setPos(e.target.value)}><option>ALL</option>{["QB","RB","WR","TE"].map(x=><option key={x}>{x}</option>)}</select><button className="small ghost" onClick={exportBoard}>Export Board</button><button className="small ghost" onClick={resetOrder}>Reset Order</button></div>
<div className="card scroll"><table><thead><tr><th>#</th><th>Pos</th><th>Player</th><th>College</th><th>Planning Tier</th><th>Authoritative Grade</th><th>Order</th></tr></thead><tbody>{visible.map(r=><tr key={r.id}><td>{ranked.findIndex(x=>x.id===r.id)+1}</td><td><b>{r.position}</b></td><td className="player-name"><span className="player-badge" style={schoolStyle(r.college)}>{r.name}</span></td><td>{r.college||"—"}</td><td><select value={tiers[String(r.id)]||""} onChange={e=>setTier(String(r.id),e.target.value)} aria-label={`Planning tier for ${r.name}`}><option value="">—</option>{["Tier 1","Tier 2","Tier 3","Tier 4","Tier 5","Watch"].map(t=><option key={t}>{t}</option>)}</select></td><td>{!grades[String(r.id)]||grades[String(r.id)].pre==null?<span className="muted">Incomplete scouting</span>:<b>{Number(grades[String(r.id)].final??grades[String(r.id)].pre).toFixed(2)}</b>}</td><td><div className="row-actions"><button className="small ghost" onClick={()=>move(r,-1)} aria-label={`Move ${r.name} up`}>↑</button><button className="small ghost" onClick={()=>move(r,1)} aria-label={`Move ${r.name} down`}>↓</button></div></td></tr>)}</tbody></table>{!visible.length&&<div className="empty"><b>No watched 2027 players yet.</b><span>Use New Player Watched from Scouting Tools and they will appear here.</span></div>}</div></>}
