"use client";import {useEffect,useMemo,useState} from "react";
const norm=(s:any)=>String(s||"").toLowerCase().replace(/&/g,"and").replace(/[^a-z0-9]+/g," ").trim().replace(/\s+/g," ");
const POS:Record<string,number>={QB:0,RB:1,WR:2,TE:3};
function teamKeys(c:any){return new Set([c.team?.location,c.team?.displayName,c.team?.shortDisplayName,c.team?.name,c.team?.abbreviation].filter(Boolean).map(norm))}
function rankMap(rs:any[]){const poll=rs.find(r=>/college football playoff/i.test(r.name||r.shortName||""))||rs.find(r=>/AP Top 25/i.test(r.name||r.shortName||""));const m:Record<string,number>={};for(const x of poll?.ranks||[]){const t=x.team||x;for(const k of [t.location,t.displayName,t.name,t.abbreviation].filter(Boolean))m[norm(k)]=Number(x.current||x.rank||x.ranking)}return m}
export default function Page(){const [rows,setRows]=useState<any[]>([]),[events,setEvents]=useState<any[]>([]),[players,setPlayers]=useState<any[]>([]),[rankings,setRankings]=useState<any[]>([]);
const load=()=>fetch("/api/watch-list",{cache:"no-store"}).then(r=>r.json()).then(x=>setRows(Array.isArray(x)?x:[]));useEffect(()=>{load();try{setEvents(JSON.parse(localStorage.getItem("v4-scouting-events")||"[]"));setPlayers(JSON.parse(localStorage.getItem("v4-scouting-players")||"[]"));setRankings(JSON.parse(localStorage.getItem("v4-scouting-rankings")||"[]"))}catch{}},[]);
const ranks=useMemo(()=>rankMap(rankings),[rankings]);
const enriched=useMemo(()=>rows.map(x=>{const e=events.find((g:any)=>String(g.id)===String(x.espn_event_id));if(!e)return {...x,sides:[],network:"TBD"};const comp=e.competitions?.[0]||{},sides=(comp.competitors||[]).map((c:any)=>{const keys=teamKeys(c),prospects=players.filter((p:any)=>p.draft_class===2027&&p.college&&keys.has(norm(p.college))).sort((a:any,b:any)=>(POS[a.position]??99)-(POS[b.position]??99)||String(a.name).localeCompare(String(b.name)));const rank=[...keys].map(k=>ranks[k]).find(Boolean);return {name:c.team?.displayName||c.team?.location||c.team?.name,logo:c.team?.logo||c.team?.logos?.[0]?.href||"",homeAway:c.homeAway,rank,prospects}});const b=(comp.broadcasts||[]).flatMap((z:any)=>z.names||[]).filter(Boolean);return {...x,sides,network:b[0]||comp.geoBroadcasts?.[0]?.media?.shortName||"TBD"}}),[rows,events,players,ranks]);
async function remove(id:any){await fetch("/api/watch-list?id="+id,{method:"DELETE"});load()}
async function watchNow(x:any){const home=x.sides.find((s:any)=>s.homeAway==="home")||x.sides[1],away=x.sides.find((s:any)=>s.homeAway==="away")||x.sides[0],date=new Date(x.kickoff).toLocaleDateString([],{month:"long",day:"numeric",year:"numeric"}),section=(s:any)=>s.name+"\n"+(s.prospects.length?s.prospects.map((p:any)=>"• "+(p.jersey_number?"#"+p.jersey_number+" ":"")+p.position+" "+p.name+"\n  ◦ ").join("\n"):"• No Draft Eligible Players"),title=(away?.name||x.away_team)+" vs "+(home?.name||x.home_team)+" - "+date;await fetch("/api/game-notes",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({id:x.espn_event_id,kickoff:x.kickoff,homeTeam:home?.name||x.home_team,awayTeam:away?.name||x.away_team,title,notes:section(away)+"\n\n"+section(home)})});location.href="/game-notes"}
return <><div className="page-head"><div><h1>Watch List</h1><p className="muted">Games you saved to watch later, with the same scouting context as the homepage.</p></div></div><div className="watch-list-grid">{enriched.map(x=><article className="card watch-list-card" key={x.id}><div className="eyebrow">{new Date(x.kickoff).toLocaleString([],{weekday:"long",month:"short",day:"numeric",hour:"numeric",minute:"2-digit"})}</div><h2>{x.away_team} vs {x.home_team}</h2><div className="muted" style={{marginBottom:12}}>Watch on <strong>{x.network}</strong></div>{x.sides.map((s:any)=><section className="matchup-team" key={s.name} style={{marginBottom:10}}><div style={{display:"flex",alignItems:"center",gap:9,marginBottom:8}}>{s.logo&&<img src={s.logo} alt="" style={{width:32,height:32,objectFit:"contain"}}/>}<strong>{s.rank?"#"+s.rank+" ":""}{s.name}</strong></div>{s.prospects.length?s.prospects.map((p:any)=><div key={p.id} className="muted">{p.jersey_number?"#"+p.jersey_number+" ":""}{p.position} · {p.name}</div>):<div className="muted">No Draft Eligible Players</div>}</section>)}<div style={{display:"flex",gap:8,marginTop:12}}><button className="success" onClick={()=>watchNow(x)}>Watch Now</button><button className="ghost" onClick={()=>remove(x.id)}>Remove</button></div></article>)}{!rows.length&&<div className="card muted">No saved games yet. Choose Watch Later from the Home page.</div>}</div></>}