import {ensureTursoSchema,rows} from "@/lib/turso";
import {findCollegeTeam,teamScheduleWithPlayerStats,resolvePlayerMedia} from "@/lib/college-team";
import {draftAdjustedFinalGrade,preDraftGrade,workbookScoutingGrade} from "@/lib/scouting-formulas";
import {loadScoutingGlossary} from "@/lib/scouting-glossary-store";
import {findHistoricalScoutingSnapshot,historicalEvaluations,historicalGradeData} from "@/lib/historical-scouting";
import {GET as getFinalBoard} from "@/app/api/final-board/live/route";
import {GET as getPlayerData} from "@/app/api/player-data/route";
import {createHash} from "node:crypto";
import {playerNameKey} from "@/lib/player-name";
type Pos="QB"|"RB"|"WR"|"TE";const FILM:Record<Pos,string[]>={QB:["Arm Strength","Arm Velocity","Accuracy","Decision Making","Poise + OOS","Mechanics","Mobility","Leadership","Size"],RB:["Ball Carrier Vision","Carrying","Elusiveness","Big Play Speed","Patience","Contact Balance","Effort","Receiving Skills","Pass Blocking"],WR:["Catching","Route Running","Elusiveness","Game Speed","Competitiveness","Size","Blocking"],TE:["Catching","Route Running","Blocking","Athleticism","Competitiveness","Size","Versatility"]};
type FactorSpec={label:string;keys:string[];pct?:boolean;inverse?:boolean};
const PRODUCTION_FACTORS:Record<Pos,FactorSpec[]>={
QB:[{label:"Completion %",keys:["Completion %","Comp %"],pct:true},{label:"Yards / Attempt",keys:["Yards/Attempt"]},{label:"Passing Yards",keys:["Yards","Passing Yards"]},{label:"Passing TDs",keys:["Touchdowns","Passing TDs"]},{label:"Interceptions",keys:["Interceptions"],inverse:true},{label:"Rush Yards",keys:["Rush Yards","Rushing Yards"]},{label:"Rush Yards / Attempt",keys:["Rush Yards/Attempt","Rush Yds/Att"]},{label:"Rush Yard %",keys:["Rush Yard %"],pct:true}],
RB:[{label:"Yards / Carry",keys:["Yards/Carry","Yards/Attempt"]},{label:"Yards / Reception",keys:["Yards/Reception"]},{label:"Yards / Touch",keys:["Yards/Touch"]},{label:"YPTP",keys:["YPTP"]},{label:"Reception Share",keys:["Rec Share %"],pct:true},{label:"Dominator Rating",keys:["Dom Rtg"],pct:true},{label:"FR + Soph Rush Yards",keys:["FR + Soph Rush Yd"]},{label:"Single-Season Receptions",keys:["Single Season Rec"]},{label:"Career Receptions",keys:["Career Rec"]},{label:"Speed Score",keys:["Speed Score"]}],
WR:[{label:"Yards / Reception",keys:["Yards/Rec","Yards/Reception"]},{label:"Yards / Target",keys:["Yards/Tgt","Yards/target"]},{label:"Target Share",keys:["Target %"],pct:true},{label:"Catch %",keys:["Catch %"],pct:true},{label:"YPTPA",keys:["YPTPA"]},{label:"Weighted Dominator",keys:["Weighted Dom Rtg","Weightd Dom Rtg"],pct:true},{label:"Dominator Rating",keys:["Dom Rtg"],pct:true},{label:"Freshman Yards",keys:["FR Yards"]},{label:"Sophomore Yards",keys:["Soph Yards"]},{label:"Freshman TDs",keys:["FR TDs"]},{label:"Sophomore TDs",keys:["Soph TDs"]},{label:"Speed Score",keys:["Speed Score"]}],
TE:[{label:"Yards / Reception",keys:["Yards/Rec","Yards/Reception"]},{label:"Yards / Target",keys:["Yards/Tgt","Yards/target"]},{label:"Target Share",keys:["Target %"],pct:true},{label:"Catch %",keys:["Catch %"],pct:true},{label:"YPTPA",keys:["YPTPA"]},{label:"Weighted Dominator",keys:["Weighted Dom Rtg","Weightd Dom Rtg"],pct:true},{label:"Dominator Rating",keys:["Dom Rtg"],pct:true},{label:"Max Yards / Reception",keys:["Max Yds/Rec"]},{label:"Speed Score",keys:["Speed Score"]}]
};
const ANALYTICAL_FACTORS:Record<Pos,FactorSpec[]>={
QB:[{label:"ADOT",keys:["ADOT"]},{label:"QBR",keys:["QBR"]},{label:"Adjusted Y/A",keys:["Adjusted Y/A"]},{label:"Screen %",keys:["Screen %","Screen throw %"],pct:true,inverse:true},{label:"Adjusted Comp %",keys:["ADJ Comp %","Adjusted Comp %"],pct:true},{label:"Clean Comp %",keys:["Clean Comp %"],pct:true},{label:"Big Time Throws",keys:["Big Time Throws"]},{label:"BTT %",keys:["BTT %"],pct:true},{label:"Turnover-Worthy Plays",keys:["TO Worthy Plays"],inverse:true},{label:"TWP %",keys:["TWP %"],pct:true,inverse:true},{label:"Time to Throw",keys:["Time to Throw","Time to throw"],inverse:true},{label:"Allowed Pressure %",keys:["Allowed Press. %"],pct:true,inverse:true},{label:"20+ Completion %",keys:["20+ Comp %"],pct:true},{label:"Play-Action BTT %",keys:["PA BTT %"],pct:true},{label:"Pressure-to-Sack %",keys:["Pressure-to-Sack %"],pct:true,inverse:true},{label:"Pressured Adjusted %",keys:["Pressured ADJ%"],pct:true},{label:"Pressured BTT %",keys:["Pressured BTT%"],pct:true},{label:"Pressured TWP %",keys:["Pressured TWP%"],pct:true,inverse:true},{label:"Scrambles",keys:["Scrambles"]},{label:"Scramble Yards",keys:["Scramble Yards"]},{label:"Yards / Scramble",keys:["Yards/Scramble"]},{label:"Rush Yard %",keys:["Rush Yard %"],pct:true},{label:"Pressure Scrambles",keys:["Press. Scrambles"]},{label:"Clean Scramble %",keys:["Clean Scramble %"],pct:true,inverse:true}],
RB:[{label:"Fumble Grade",keys:["Fumble Grade"]},{label:"Elusive Rating",keys:["Elusive Rating"]},{label:"Missed Tackles Forced",keys:["MTFs"]},{label:"Breakaway Runs",keys:["Breakaway Runs"]},{label:"Breakaway Yards",keys:["Breakaway Yards"]},{label:"Breakaway %",keys:["Breakaway %"],pct:true},{label:"Rush 1st Downs",keys:["Rush 1st Downs"]},{label:"1st Downs / ATT",keys:["1st Downs/ATT"],pct:true},{label:"YAC / ATT",keys:["YAC/ATT"]},{label:"MTF / ATT",keys:["MTF/Att"],pct:true},{label:"Yards / Route Run",keys:["Y/RR","YPRR"]},{label:"YAC / Reception",keys:["YAC/Rec"]},{label:"ADOT",keys:["ADOT"]},{label:"Receiving 1st Downs",keys:["Rec First Downs"]},{label:"1st Downs / Target",keys:["1st Downs/Tgt"],pct:true},{label:"Pass Block Grade",keys:["Pass Block Grade"]}],
WR:[{label:"Drop %",keys:["Drop %"],pct:true,inverse:true},{label:"Catch in Traffic %",keys:["Catch in Traffic %"],pct:true},{label:"1st Downs",keys:["1st Downs"]},{label:"1st Downs / Target",keys:["1st Downs / Tgt","1st Downs/Tgt"],pct:true},{label:"Targets / Route",keys:["Targets/Route","Targets / Route"],pct:true},{label:"1st Downs / Route",keys:["1st Downs/Route","1st Downs / Route"],pct:true},{label:"Yards / Route Run",keys:["Y/RR"]},{label:"Y/RR vs Man",keys:["Y/RR vs Man"]},{label:"Y/RR vs Zone",keys:["Y/RR vs Zone"]},{label:"Contested Target %",keys:["Contested Target %"],pct:true},{label:"Air Yards %",keys:["Air Yards %"],pct:true},{label:"YAC / Reception",keys:["YAC/Rec"]},{label:"Missed Tackles Forced",keys:["MTFs"]},{label:"Yards / Reception",keys:["Yards/Rec"]},{label:"ADOT",keys:["ADOT"]},{label:"Screen %",keys:["Screen %"],pct:true,inverse:true},{label:"Catches in Traffic",keys:["Catches in Traffic"]},{label:"Run Block Grade",keys:["Run Block Grade"]}],
TE:[{label:"Drop %",keys:["Drop %"],pct:true,inverse:true},{label:"Catch in Traffic %",keys:["Catch in Traffic %"],pct:true},{label:"1st Downs",keys:["1st Downs"]},{label:"1st Downs / Target",keys:["1st Downs / Tgt","1st Downs/Tgt"],pct:true},{label:"Yards / Route Run",keys:["Y/RR"]},{label:"Y/RR vs Man",keys:["Y/RR vs Man"]},{label:"Y/RR vs Zone",keys:["Y/RR vs Zone"]},{label:"Air Yards %",keys:["Air Yard %","Air Yards %"],pct:true},{label:"YAC / Reception",keys:["YAC/Rec"]},{label:"Missed Tackles Forced",keys:["MTFs"]},{label:"Yards / Reception",keys:["Yards/Rec"]},{label:"ADOT",keys:["ADOT"]},{label:"Catches in Traffic",keys:["Catches in Traffic"]},{label:"Inline Snap %",keys:["Inline Snap %","Inline Rate"],pct:true,inverse:true},{label:"Slot Snap %",keys:["Slot Snap %","Slot Rate"],pct:true},{label:"Wide Snap %",keys:["Wide Snap %","Wide Rate"],pct:true},{label:"Run Block Grade",keys:["Run Block Grade"]},{label:"Pass Block Grade",keys:["Pass Block Grade"]}]
};

function sourceValue(row:any,keys:string[]){for(const key of keys){const v=row?.[key];if(v!==undefined&&v!==null&&String(v).trim()!=="")return v}return null}
function factorNumber(v:any,pct=false){if(v==null||v==="")return null;const raw=String(v).trim(),n=Number(raw.replace(/[%,$]/g,"").replace(/,/g,""));if(!Number.isFinite(n))return null;if(pct&&!raw.includes("%")&&Math.abs(n)<=1.5)return n*100;return n}
function percentileFor(sourceRows:any[],spec:FactorSpec,raw:any){const n=factorNumber(raw,spec.pct);if(n==null)return null;const vals=sourceRows.map(row=>factorNumber(sourceValue(row,spec.keys),spec.pct)).filter((v):v is number=>v!=null).sort((a,b)=>a-b);if(!vals.length)return null;if(vals.length===1)return 100;let first=vals.findIndex(v=>v===n);if(first<0)first=vals.filter(v=>v<n).length;let last=first;while(last+1<vals.length&&vals[last+1]===n)last++;const pct=((first+last)/2)/(vals.length-1);return Math.round((spec.inverse?1-pct:pct)*100)}
function displayFactor(raw:any,pct=false){if(raw==null||raw==="")return "—";if(typeof raw==="number")return pct?(Math.abs(raw)<=1.5?(raw*100).toFixed(1)+"%":raw.toFixed(1)+"%"):String(Number(raw.toFixed(2)));return String(raw)}
function buildGradeFactors(p:any,es:any[],sourceRows:any[]){const vals:Record<string,any>={};for(const e of es)vals[String(e.category)]=e.value??e.commentary;const fallback={Player:p.name,...vals},source=sourceRows.find(row=>playerNameKey(row?.Player)===playerNameKey(p.name))||fallback,population=sourceRows.length?sourceRows:[source];const mapSpec=(spec:FactorSpec)=>{const raw=sourceValue(source,spec.keys);return {label:spec.label,value:displayFactor(raw,spec.pct),raw,percentile:percentileFor(population,spec,raw),inverse:Boolean(spec.inverse)}};return {film:FILM[p.position as Pos].map(label=>({label,value:vals[label]??null})),production:(PRODUCTION_FACTORS[p.position as Pos]||[]).map(mapSpec),analytical:(ANALYTICAL_FACTORS[p.position as Pos]||[]).map(mapSpec)}}
async function loadFinalBoardRows(draftClass:number){try{const r=await getFinalBoard(new Request("http://internal/api/final-board/live?view=base&draftClass="+encodeURIComponent(String(draftClass))));const j=await r.json();return r.ok&&Array.isArray(j?.rows)?j.rows:[]}catch{return []}}
async function loadPlayerDataRows(position:string,draftClass:number){try{const r=await getPlayerData(new Request("http://internal/api/player-data?position="+encodeURIComponent(position)+"&draftClass="+encodeURIComponent(String(draftClass))));const j=await r.json();return r.ok&&Array.isArray(j?.rows)?j.rows:[]}catch{return []}}
function draftTeamFromResult(value:any){const s=String(value??"").trim(),comma=s.lastIndexOf(",");return comma>=0?s.slice(comma+1).trim():""}
async function generateGeminiSummary(name:string,position:string,notes:string){const apiKey=process.env.GEMINI_API_KEY;if(!apiKey)throw new Error("Gemini is not configured");const model=process.env.GEMINI_MODEL||"gemini-2.5-flash",prompt="You are the scouting analyst inside a private dynasty rookie-draft workspace. Synthesize every saved scouting note for "+name+" ("+position+") into a concise 3-5 sentence scouting summary. Do not quote, copy, concatenate, or preserve the wording of any individual note. Identify recurring traits across games, reconcile contradictions and development over time, and distinguish repeated evidence from one-off observations. Stay strictly grounded in the supplied notes; do not invent facts, stats, grades, or projections. Return strict JSON only with one key: summary.\n\nSAVED NOTES:\n"+notes;const r=await fetch("https://generativelanguage.googleapis.com/v1beta/models/"+encodeURIComponent(model)+":generateContent?key="+encodeURIComponent(apiKey),{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({contents:[{parts:[{text:prompt}]}],generationConfig:{temperature:.2,responseMimeType:"application/json"}}),cache:"no-store"});const raw=await r.text();if(!r.ok)throw new Error("Gemini summary failed: "+raw.slice(0,160));const json=JSON.parse(raw),parts=Array.isArray(json?.candidates?.[0]?.content?.parts)?json.candidates[0].content.parts:[],text=parts.map((x:any)=>String(x?.text||"")).join("").trim().replace(/^\`\`\`(?:json)?\s*/i,"").replace(/\s*\`\`\`$/,""),parsed=JSON.parse(text);const summary=String(parsed?.summary||"").trim();if(!summary)throw new Error("Gemini returned an empty summary");return summary}
async function scoutingSummary(q:any,p:any,notes:string){if(!notes.trim())return "No scouting notes were stored for this player.";const hash=createHash("sha256").update(notes).digest("hex"),key="player-profile-summary:"+String(p.id);try{const cached:any=rows(await q.execute({sql:"select value from settings where key=?",args:[key]}))[0];if(cached?.value){const parsed=JSON.parse(String(cached.value));if(parsed?.hash===hash&&String(parsed?.summary||"").trim())return String(parsed.summary)}}catch{}try{const summary=await generateGeminiSummary(String(p.name),String(p.position),notes);try{await q.execute({sql:"insert into settings(key,value,updated_at) values(?,?,?) on conflict(key) do update set value=excluded.value,updated_at=excluded.updated_at",args:[key,JSON.stringify({hash,summary}),new Date().toISOString()]})}catch{}return summary}catch(e){console.warn("[PLAYER PROFILE] Gemini scouting synthesis failed",e);return "AI scouting synthesis is temporarily unavailable. Your saved scouting notes are preserved and will be summarized on the next successful refresh."}}

function gradeData(p:any,es:any[],glossary:any[][]){const v:Record<string,any>={};for(const e of es)v[e.category]=e.value??e.commentary;const scouting=workbookScoutingGrade(p.position,FILM[p.position as Pos].map(k=>Number(v[k])),v,glossary),early=v["Early Declare"]??v["Early Declare?"]??false,pre=scouting==null?null:preDraftGrade(p.position,scouting,null,null,early,glossary),teamRaw=v["Team Score (10)"],capRaw=v["Draft Capital Score (10)"],team=teamRaw==null||teamRaw===""?NaN:Number(teamRaw),cap=capRaw==null||capRaw===""?NaN:Number(capRaw),draftResult=String(v["Draft Result"]??"").trim(),hasFinal=Boolean(draftResult&&!/^pending$/i.test(draftResult)&&Number.isFinite(team)&&Number.isFinite(cap)),final=pre==null?null:(hasFinal?draftAdjustedFinalGrade(p.position,pre,team,cap,glossary):pre);return {values:v,scouting,production:Number.isFinite(Number(v["Production Grade"]))?Number(v["Production Grade"]):null,analytical:Number.isFinite(Number(v["Analytical Grade"]))?Number(v["Analytical Grade"]):null,final,pre}}
async function appBoardRanks(q:any,draftClass:number){
  try{
    const ps=rows(await q.execute({sql:"select id,name,position,watch_order from players where draft_class=? and position in ('QB','RB','WR','TE')",args:[draftClass]}));
    if(draftClass<2027){
      const out:Record<string,string>={};
      for(const pos of ["QB","RB","WR","TE"]){
        const list=ps.filter((p:any)=>p.position===pos).map((p:any)=>{
          const snapshot=findHistoricalScoutingSnapshot(draftClass,String(p.position),String(p.name)),g=historicalGradeData(snapshot);
          return {...p,rankGrade:g.final??g.pre??g.scouting??null};
        }).filter((p:any)=>draftClass<=2021||p.rankGrade!=null);
        list.sort((a:any,b:any)=>{
          if(a.rankGrade==null&&b.rankGrade==null)return (Number(a.watch_order)||9999)-(Number(b.watch_order)||9999);
          if(a.rankGrade==null)return 1;if(b.rankGrade==null)return-1;
          return b.rankGrade-a.rankGrade||(Number(a.watch_order)||9999)-(Number(b.watch_order)||9999);
        });
        list.forEach((p:any,i:number)=>out[String(p.id)]=pos+(i+1));
      }
      return out;
    }
    const key="final-draft-board-state",stateRow:any=rows(await q.execute({sql:"select value from settings where key=?",args:[key]}))[0];let state:any={order:[]};if(stateRow?.value)try{state=JSON.parse(String(stateRow.value))}catch{}
    const order=Array.isArray(state?.order)?state.order.map(String):[];
    ps.sort((a:any,b:any)=>{const ai=order.indexOf(String(a.id)),bi=order.indexOf(String(b.id));if(ai<0&&bi<0)return String(a.position).localeCompare(String(b.position))||String(a.name).localeCompare(String(b.name));if(ai<0)return 1;if(bi<0)return-1;return ai-bi});
    const counts:Record<string,number>={},out:Record<string,string>={};for(const p of ps){counts[p.position]=(counts[p.position]||0)+1;out[String(p.id)]=String(p.position)+counts[p.position]}return out
  }catch{return {}}
}
async function espnStats(id:string){if(!id)return {categories:[],sourceUrl:""};try{const r=await fetch(`https://site.web.api.espn.com/apis/common/v3/sports/football/college-football/athletes/${id}/stats`,{next:{revalidate:21600},headers:{"user-agent":"Mozilla/5.0 (compatible; RookieDraft/1.0)"}});if(!r.ok)return {categories:[],sourceUrl:`https://www.espn.com/college-football/player/stats/_/id/${id}`};const j=await r.json(),teams=j?.teams||{},teamValues=Object.values(teams) as any[],teamFor=(x:any)=>teams[x?.teamSlug]||teamValues.find((t:any)=>String(t?.id)===String(x?.teamId))||null,logo=(t:any)=>t?.logos?.find?.((x:any)=>x?.rel?.includes?.("default"))?.href||t?.logos?.[0]?.href||"";const categories=(j?.categories||[]).filter((c:any)=>Array.isArray(c?.statistics)&&c.statistics.length).map((c:any)=>({name:c.name,displayName:c.displayName||c.name,labels:Array.isArray(c.labels)?c.labels:[],rows:c.statistics.map((x:any)=>{const t=teamFor(x);return {season:x?.season?.displayName||String(x?.season?.year||""),year:x?.season?.year||null,team:t?.shortDisplayName||t?.location||t?.displayName||x?.teamSlug||"",teamAbbr:t?.abbreviation||"",teamLogo:logo(t),stats:Array.isArray(x?.stats)?x.stats:[]}}),totals:Array.isArray(c?.totals)?c.totals:Array.isArray(c?.totals?.stats)?c.totals.stats:[]}));return {categories,sourceUrl:`https://www.espn.com/college-football/player/stats/_/id/${id}`}}catch{return {categories:[],sourceUrl:`https://www.espn.com/college-football/player/stats/_/id/${id}`}}}
export async function GET(req:Request){
  try{
    const id=new URL(req.url).searchParams.get("id");if(!id)return Response.json({error:"id required"},{status:400});
    const q=await ensureTursoSchema(),glossary=await loadScoutingGlossary(q);let p:any=rows(await q.execute({sql:"select * from players where id=?",args:[id]}))[0];if(!p)return Response.json({error:"Player not found"},{status:404});
    const historical=Number(p.draft_class)<2027;
    if(historical&&(!p.espn_athlete_id||!p.headshot_url)){try{const m=await resolvePlayerMedia(String(p.name),String(p.college||""));if(m.espnId||m.url||m.jersey){const now=new Date().toISOString();p={...p,espn_athlete_id:m.espnId||p.espn_athlete_id||null,espn_source:m.espnId?m.source:p.espn_source,headshot_url:m.url||p.headshot_url||null,headshot_source:m.url?m.source:p.headshot_source,jersey_number:m.jersey||p.jersey_number||null};await q.execute({sql:"update players set espn_athlete_id=?,espn_source=?,headshot_url=?,headshot_source=?,jersey_number=?,updated_at=? where id=?",args:[p.espn_athlete_id,p.espn_source,p.headshot_url,p.headshot_source,p.jersey_number,now,p.id]})}}catch{}}
    const snapshot=historical?findHistoricalScoutingSnapshot(Number(p.draft_class),String(p.position),String(p.name)):null,es=historical?historicalEvaluations(snapshot):rows(await q.execute({sql:"select category,value,commentary from evaluations where player_id=? order by category",args:[id]}));
    const [boardRows,sourceRows]=await Promise.all([loadFinalBoardRows(Number(p.draft_class)),loadPlayerDataRows(String(p.position),Number(p.draft_class))]),baseGrades=historical?historicalGradeData(snapshot):gradeData(p,es,glossary),boardRow=boardRows.find((x:any)=>String(x.id)===String(p.id));
    const g={...baseGrades,scouting:boardRow?.scoutingGrade??baseGrades.scouting,production:boardRow?.productionGrade??baseGrades.production,analytical:boardRow?.analyticalGrade??baseGrades.analytical,pre:boardRow?.preDraftGrade??baseGrades.pre,final:boardRow?.finalGrade??baseGrades.final,draftResult:boardRow?.draftResult??baseGrades.values?.["Draft Result"]??null,draftTeam:boardRow?.draftTeam??draftTeamFromResult(boardRow?.draftResult??baseGrades.values?.["Draft Result"]),overallRank:boardRow?.overallRank??null,boardPositionRank:boardRow?.positionRank??null};
    let rankMap:Record<string,string>={};if(boardRows.length){for(const row of boardRows)if(row?.position&&row?.positionRank!=null)rankMap[String(row.id)]=String(row.position)+String(row.positionRank)}else rankMap=await appBoardRanks(q,Number(p.draft_class));
    const teamPlayersRaw=p.college?rows(await q.execute({sql:"select id,name,position,college,scouting_status,headshot_url,jersey_number from players where draft_class=? and lower(coalesce(college,''))=lower(?) and id<>? order by position,watch_order,name",args:[p.draft_class,p.college,p.id]})):[],teamPlayers=teamPlayersRaw.map((x:any)=>({...x,positionRank:rankMap[String(x.id)]||x.position}));
    const sessions=rows(await q.execute({sql:"select raw_notes,overall_writeup,game_date,opponent,created_at from scouting_sessions where player_id=? order by coalesce(game_date,created_at),id",args:[id]})),transferHistory=rows(await q.execute({sql:"select id,from_college,to_college,effective_season,recorded_at from player_school_history where player_id=? order by recorded_at desc,id desc",args:[id]}));
    const chunks:string[]=[],legacy=String(historical?snapshot?.commentary:g.values?.["__COMMENTARY__"]??"").trim();if(legacy)chunks.push("Legacy scouting commentary:\n"+legacy);for(const s of sessions){const raw=String(s.raw_notes||"").trim(),writeup=String(s.overall_writeup||"").trim();if(!raw&&!writeup)continue;const heading=[s.game_date,s.opponent?("vs "+s.opponent):""].filter(Boolean).join(" ")||"Scouting session";chunks.push(heading+":\n"+[raw,writeup&&writeup!==raw?writeup:""].filter(Boolean).join("\n"))}
    const notes=chunks.join("\n\n"),notesSummary=await scoutingSummary(q,p,notes),gradeFactors=buildGradeFactors(p,es,sourceRows),scheduleSeason=Math.max(2000,Number(p.draft_class)-1),team=p.college?await findCollegeTeam(p.college).catch(()=>null):null,schedule=team?await teamScheduleWithPlayerStats(team.id,String(p.espn_athlete_id||""),String(p.position),scheduleSeason):[],player={...p,positionRank:rankMap[String(p.id)]||p.position};
    return Response.json({player,grades:g,gradeFactors,evaluations:es,notesSummary,teamPlayers,schedule,scheduleSeason,teamLogo:team?.logo||"",transferHistory,historicalSnapshot:snapshot,stats:await espnStats(p.espn_athlete_id||"")});
  }catch(e:any){return Response.json({error:"Could not load player profile",detail:e?.message},{status:500})}
}
