"use client";
import {useEffect,useState} from "react";
import {schoolStyle} from "@/lib/school-colors";
import {ALL_STAR_GAMES,POSITIONS,type AddPlayerInput,type AddPlayerIssue,type AllStarGame,type Position} from "@/lib/player-add";
type Review={player:AddPlayerInput;issues:AddPlayerIssue[];checked:boolean};
type Totals={added:number;existing:number;failed:{name:string;message:string}[]};
const pair=(s:string)=>{const i=s.indexOf(",");return i<0?[s.trim(),""]:[s.slice(0,i).trim(),s.slice(i+1).trim()]};
const label=(t:string)=>t==="exact_duplicate"?"Already on sheet":t==="possible_duplicate"?"Possible duplicate":t==="queue_duplicate"?"Duplicate in queue":t==="college_mismatch"?"School check":t==="validation_error"?"Validation":"School not found";
export default function AddPlayersModal({open,onClose,onDone,seed=[]}:{open:boolean;onClose:()=>void;onDone?:()=>void;seed?:Array<{name:string;position:string;college:string;allStarGame?:string}>}){
 const [tab,setTab]=useState<"single"|"position"|"college">("single"),[queue,setQueue]=useState<AddPlayerInput[]>([]),[review,setReview]=useState<Review[]|null>(null),[busy,setBusy]=useState(false),[msg,setMsg]=useState(""),[done,setDone]=useState(false),[totals,setTotals]=useState<Totals>({added:0,existing:0,failed:[]});
 const [name,setName]=useState(""),[college,setCollege]=useState(""),[position,setPosition]=useState<Position>("QB"),[allStar,setAllStar]=useState<AllStarGame>("None");
 const [bulkPos,setBulkPos]=useState<Position>("QB"),[bulkPosGame,setBulkPosGame]=useState<AllStarGame>("None"),[bulkPosText,setBulkPosText]=useState("");
 const [bulkCollege,setBulkCollege]=useState(""),[bulkCollegeGame,setBulkCollegeGame]=useState<AllStarGame>("None"),[bulkCollegeText,setBulkCollegeText]=useState("");
 useEffect(()=>{if(open){const seeded:AddPlayerInput[]=seed.filter(p=>POSITIONS.includes(p.position as Position)).map(p=>({name:p.name,college:p.college,position:p.position as Position,allStarGame:ALL_STAR_GAMES.includes((p.allStarGame||"None") as AllStarGame)?(p.allStarGame||"None") as AllStarGame:"None"}));setTab("single");setQueue(seeded);setReview(null);setBusy(false);setMsg("");setDone(false);setTotals({added:0,existing:0,failed:[]});setName("");setCollege("");setBulkPosText("");setBulkCollege("");setBulkCollegeText("")}},[open,seed]);
 function addRows(rows:AddPlayerInput[]){const good=rows.filter(x=>x.name.trim()&&x.college.trim());if(!good.length)return setMsg("Nothing valid to add to the queue.");setQueue(q=>q.concat(good));setMsg(good.length+" player"+(good.length===1?"":"s")+" added to the queue.")}
 function addSingle(){if(!name.trim()||!college.trim())return setMsg("Enter both a player name and college.");addRows([{name:name.trim(),college:college.trim(),position,allStarGame:allStar}]);setName("");setCollege("")}
 function addPositionGroup(){const rows:AddPlayerInput[]=[];const bad:string[]=[];bulkPosText.split(/\r?\n/).map(x=>x.trim()).filter(Boolean).forEach(line=>{const [n,c]=pair(line);if(!n||!c)bad.push(line);else rows.push({name:n,college:c,position:bulkPos,allStarGame:bulkPosGame})});if(bad.length)return setMsg('Use "Name, College" on every line.');addRows(rows);setBulkPosText("")}
 function addCollegeGroup(){if(!bulkCollege.trim())return setMsg("Enter the college for this group.");const rows:AddPlayerInput[]=[];const bad:string[]=[];bulkCollegeText.split(/\r?\n/).map(x=>x.trim()).filter(Boolean).forEach(line=>{const [n,p]=pair(line),pos=p.toUpperCase() as Position;if(!n||!POSITIONS.includes(pos))bad.push(line);else rows.push({name:n,college:bulkCollege.trim(),position:pos,allStarGame:bulkCollegeGame})});if(bad.length)return setMsg('Use "Name, Position" with QB, RB, WR, or TE on every line.');addRows(rows);setBulkCollegeText("")}
 function countResult(j:any){setTotals(t=>({added:t.added+(j.successful||[]).filter((x:any)=>x.action==="added").length,existing:t.existing+(j.successful||[]).filter((x:any)=>x.action==="existing").length,failed:t.failed.concat(j.failed||[])}))}
 async function save(players:AddPlayerInput[],force:boolean){if(!players.length)return;const r=await fetch("/api/players/add-batch",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({players,force})}),j=await r.json();if(!r.ok)throw new Error(j.error||"Could not add players.");countResult(j)}
 function finish(){setReview(null);setQueue([]);setDone(true);setMsg("");window.dispatchEvent(new Event("rookie-draft:players-changed"));onDone?.()}
 async function submit(){if(!queue.length)return;setBusy(true);setMsg("");try{const r=await fetch("/api/players/preflight",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({players:queue})}),j=await r.json();if(!r.ok)throw new Error(j.error||"Could not check queue.");const normalized=(j.players||queue) as AddPlayerInput[],map=new Map<number,AddPlayerIssue[]>((j.issues||[]).map((x:any)=>[Number(x.index),x.issues||[]] as [number,AddPlayerIssue[]])),clean=normalized.filter((_:AddPlayerInput,i:number)=>!map.has(i)),flagged=normalized.map((player:AddPlayerInput,i:number)=>({player,issues:map.get(i)||[],checked:true})).filter((x:Review)=>x.issues.length);await save(clean,false);setQueue(flagged.map((x:Review)=>x.player));if(flagged.length){setReview(flagged);setMsg(flagged.length+" player"+(flagged.length===1?" needs":"s need")+" review before being added.")}else finish()}catch(e:any){setMsg(e?.message||"Could not process queue.")}finally{setBusy(false)}}
 async function addChecked(){setBusy(true);setMsg("");try{await save((review||[]).filter(x=>x.checked).map(x=>x.player),true);finish()}catch(e:any){setMsg(e?.message||"Could not add reviewed players.")}finally{setBusy(false)}}
 function useSuggestion(i:number,s:string){setReview(v=>(v||[]).map((x,j)=>j===i?{...x,player:{...x.player,college:s},issues:x.issues.filter(z=>z.type!=="college_mismatch"&&z.type!=="college_not_found")}:x))}
 if(!open)return null;
 const tabButton=(id:"single"|"position"|"college",text:string)=><button type="button" className={tab===id?"":"ghost"} style={{flex:1}} onClick={()=>setTab(id)}>{text}</button>;
 return <div className="tool-modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&!busy&&onClose()}><div className="tool-modal" style={{width:"min(760px,94vw)",maxHeight:"90vh",overflow:"auto",padding:24}}>
  <div className="page-head"><div><div className="ey">Scouting Tools</div><h2>Add Player(s) to Scout</h2><p className="muted">Queue players first. Duplicate and school checks run before anything questionable is saved.</p></div><button className="small ghost" disabled={busy} onClick={onClose}>Close</button></div>
  {done?<div><div className="notice"><b>Add Player complete.</b> {totals.added} new added{totals.existing?", "+totals.existing+" existing confirmed/updated":""}.{totals.failed.length?" "+totals.failed.length+" failed.":""}</div>{totals.failed.map((x,i)=><div className="notice" key={x.name+i}><b>{x.name}:</b> {x.message}</div>)}<button className="success" onClick={onClose}>Done</button></div>
  :review?<div><div className="notice"><b>Review flagged players.</b> Checked players will be added. Uncheck anything you do not want.</div><div style={{display:"grid",gap:10,marginTop:12}}>{review.map((x,i)=><div className="card" key={i+x.player.name} style={{padding:14}}><div style={{display:"flex",gap:10,alignItems:"flex-start"}}><input type="checkbox" checked={x.checked} onChange={e=>setReview(v=>(v||[]).map((z,j)=>j===i?{...z,checked:e.target.checked}:z))}/><div style={{flex:1}}><div><span className="player-badge" style={schoolStyle(x.player.college)}>{x.player.name}</span> <span className="muted">{x.player.position} / {x.player.college}</span></div>{x.issues.map((z,k)=><div key={k} style={{marginTop:8,padding:8,border:"1px solid var(--line)",borderRadius:8}}><b>{label(z.type)}:</b> {z.message}{z.suggestion&&<button className="small ghost" style={{marginLeft:8}} onClick={()=>useSuggestion(i,z.suggestion!)}>Use {z.suggestion}</button>}</div>)}</div></div></div>)}</div><div style={{display:"flex",justifyContent:"space-between",gap:10,marginTop:16}}><button className="ghost" disabled={busy} onClick={()=>{setQueue((review||[]).map(x=>x.player));setReview(null);setMsg("Flagged players returned to the queue.")}}>Back to Queue</button><button className="success" disabled={busy||!review.some(x=>x.checked)} onClick={addChecked}>{busy?"Adding...":"Add Checked ("+review.filter(x=>x.checked).length+")"}</button></div>{msg&&<div className="notice" style={{marginTop:10}}>{msg}</div>}</div>
  :<div><div style={{display:"flex",gap:6,marginBottom:16}}>{tabButton("single","Single Player")}{tabButton("position","Bulk: Same Position")}{tabButton("college","Bulk: Same College")}</div>
   {tab==="single"&&<div className="grid"><label>Player Name<input value={name} onChange={e=>setName(e.target.value)} placeholder="Player name"/></label><label>College<input value={college} onChange={e=>setCollege(e.target.value)} placeholder="College"/></label><label>Position<select value={position} onChange={e=>setPosition(e.target.value as Position)}>{POSITIONS.map(x=><option key={x}>{x}</option>)}</select></label><label>All-Star Game<select value={allStar} onChange={e=>setAllStar(e.target.value as AllStarGame)}>{ALL_STAR_GAMES.map(x=><option key={x}>{x}</option>)}</select></label><button type="button" onClick={addSingle}>+ Add to Queue</button></div>}
   {tab==="position"&&<div><div className="grid"><label>Position<select value={bulkPos} onChange={e=>setBulkPos(e.target.value as Position)}>{POSITIONS.map(x=><option key={x}>{x}</option>)}</select></label><label>All-Star Game<select value={bulkPosGame} onChange={e=>setBulkPosGame(e.target.value as AllStarGame)}>{ALL_STAR_GAMES.map(x=><option key={x}>{x}</option>)}</select></label></div><label>Players - Name, College<textarea rows={7} value={bulkPosText} onChange={e=>setBulkPosText(e.target.value)} placeholder={"Player One, Texas\nPlayer Two, Oregon"}/></label><button type="button" onClick={addPositionGroup}>+ Add Group to Queue</button></div>}
   {tab==="college"&&<div><div className="grid"><label>College<input value={bulkCollege} onChange={e=>setBulkCollege(e.target.value)} placeholder="College"/></label><label>All-Star Game<select value={bulkCollegeGame} onChange={e=>setBulkCollegeGame(e.target.value as AllStarGame)}>{ALL_STAR_GAMES.map(x=><option key={x}>{x}</option>)}</select></label></div><label>Players - Name, Position<textarea rows={7} value={bulkCollegeText} onChange={e=>setBulkCollegeText(e.target.value)} placeholder={"Player One, QB\nPlayer Two, WR"}/></label><button type="button" onClick={addCollegeGroup}>+ Add Group to Queue</button></div>}
   <hr style={{margin:"20px 0"}}/><div style={{display:"flex",justifyContent:"space-between"}}><h3>Queue ({queue.length})</h3>{queue.length>0&&<button className="small ghost" onClick={()=>setQueue([])}>Clear</button>}</div>{queue.length?queue.map((p,i)=><div key={i+p.name} style={{display:"flex",justifyContent:"space-between",gap:10,padding:"9px 0",borderBottom:"1px solid var(--line)"}}><span><span className="player-badge" style={schoolStyle(p.college)}>{p.name}</span> <span className="muted">{p.college} / {p.position}{p.allStarGame&&p.allStarGame!=="None"?" / "+p.allStarGame:""}</span></span><button className="small ghost" onClick={()=>setQueue(q=>q.filter((_,j)=>j!==i))}>Remove</button></div>):<div className="muted">No players queued yet.</div>}
   {msg&&<div className="notice" style={{marginTop:10}}>{msg}</div>}<div style={{display:"flex",justifyContent:"space-between",gap:10,marginTop:16}}><button className="ghost" disabled={busy} onClick={onClose}>Cancel</button><button className="success" disabled={busy||!queue.length} onClick={submit}>{busy?"Checking...":"Add All to Sheet"}</button></div>
  </div>}
 </div></div>
}