"use client";import {useEffect,useMemo,useState} from "react";
type P={name:string,position:string,college:string,id?:any};
const norm=(s:any)=>String(s||"").toLowerCase().replace(/[^a-z0-9]/g,"");
export default function AddPlayersModal({open,onClose,seed=[],onDone}:{open:boolean,onClose:()=>void,seed?:P[],onDone?:()=>void}){const [all,setAll]=useState<P[]>([]),[existing,setExisting]=useState<any[]>([]),[pos,setPos]=useState("All Positions"),[college,setCollege]=useState(""),[search,setSearch]=useState(""),[queue,setQueue]=useState<P[]>([]);
useEffect(()=>{if(!open)return;Promise.all([fetch("/api/players",{cache:"no-store"}).then(r=>r.json()),Promise.all(["QB","RB","WR","TE"].map(async position=>(await fetch("/api/player-data?position="+position,{cache:"no-store"}).then(r=>r.json()).catch(()=>({rows:[]}))).rows||[]))]).then(([ps,groups])=>{const ex=Array.isArray(ps)?ps:[];setExisting(ex);const seen=new Set<string>(),pool:P[]=[];for(const [i,rows] of (groups as any[]).entries())for(const r of rows){const name=String(r.Player||r.player||"").trim(),c=String(r.College||r.college||"").trim(),position=["QB","RB","WR","TE"][i];if(name&&!seen.has(norm(name))){seen.add(norm(name));pool.push({name,position,college:c})}}setAll(pool);const watched=new Set(ex.filter((p:any)=>p.draft_class===2027&&p.scouting_status==="WATCHED").map((p:any)=>norm(p.name)));setQueue(seed.filter(p=>!watched.has(norm(p.name))))})},[open]);
const watched=useMemo(()=>new Set(existing.filter((p:any)=>p.draft_class===2027&&p.scouting_status==="WATCHED").map((p:any)=>norm(p.name))),[existing]);
const shown=useMemo(()=>all.filter(p=>!watched.has(norm(p.name))&&(pos==="All Positions"||p.position===pos)&&(!college||p.college.toLowerCase().includes(college.toLowerCase()))&&(!search||(p.name+" "+p.college).toLowerCase().includes(search.toLowerCase()))),[all,watched,pos,college,search]);
function add(ps:P[]){setQueue(q=>{const keys=new Set(q.map(x=>norm(x.name)));return [...q,...ps.filter(x=>!keys.has(norm(x.name)))]})}
async function process(){for(const p of queue){const old=existing.find((x:any)=>x.draft_class===2027&&norm(x.name)===norm(p.name));if(old)await fetch("/api/players",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:old.id,status:"WATCHED",position:p.position})});else await fetch("/api/players",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:p.name,position:p.position,college:p.college,draftClass:2027,status:"WATCHED"})})}onDone?.();onClose()}
if(!open)return null;return <div style={{position:"fixed",inset:0,background:"rgba(0,0,0,.55)",zIndex:500,display:"flex",alignItems:"center",justifyContent:"center"}}><div className="card" style={{width:"min(720px,92vw)",maxHeight:"88vh",overflow:"auto",padding:24}}><div style={{display:"flex",justifyContent:"space-between"}}><h2>Add Players to Scouting Sheets</h2><button className="ghost" onClick={onClose}>✕</button></div><p className="muted">ℹ️ Excluding {watched.size} already watched player(s)</p><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10}}><label>Position<select value={pos} onChange={e=>setPos(e.target.value)}><option>All Positions</option><option>QB</option><option>RB</option><option>WR</option><option>TE</option></select></label><label>College<input value={college} onChange={e=>setCollege(e.target.value)} placeholder="All Colleges (type to search)"/></label></div><label>Search<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Type to filter..."/></label><div className="muted">Showing {shown.length} player(s)</div><select multiple size={8} style={{width:"100%"}} id="player-picker">{shown.map(p=><option key={p.position+"-"+p.name} value={p.position+"|"+p.name}>{p.name}, {p.college}</option>)}</select><div style={{display:"flex",gap:8,margin:"10px 0 16px"}}><button className="success" onClick={()=>{const el=document.getElementById("player-picker") as HTMLSelectElement;const keys=[...el.selectedOptions].map(o=>o.value);add(shown.filter(p=>keys.includes(p.position+"|"+p.name)))}}>+ Add Selected to Queue</button><button className="ghost" onClick={()=>add(shown)}>+ Add All Shown to Queue</button></div><hr/><h3>Queued to Add ({queue.length})</h3><div>{queue.length?queue.map(p=><div key={p.position+"-"+p.name} style={{display:"flex",justifyContent:"space-between",padding:"8px 0",borderBottom:"1px solid var(--line)"}}><span><b>{p.name}</b><br/><small className="muted">{p.college} · {p.position}</small></span><button className="ghost" onClick={()=>setQueue(q=>q.filter(x=>norm(x.name)!==norm(p.name)))}>Remove</button></div>):<div className="muted" style={{padding:20,textAlign:"center"}}>No players queued yet</div>}</div><div style={{display:"flex",gap:8,marginTop:14}}><button className="ghost" onClick={onClose}>Cancel</button><button className="success" disabled={!queue.length} onClick={process}>Process Queue</button></div></div></div>}
