"use client";
import {useEffect,useMemo,useState} from "react";
import {useDraftClass} from "@/lib/use-draft-class";

type Status="ENTERING_DRAFT"|"RETURNING_TO_SCHOOL"|"TRANSFER_PORTAL";
type Player={playerId:string|number;name:string;position:string;college?:string;status?:Status;sourceUrl?:string;sourceTitle?:string};
type Finding={playerId:string;playerName:string;status:Status;sourceUrl:string;sourceTitle:string;sourceType?:string;announcementDate?:string;evidence?:string};
type Data={players:Player[];unannounced:Player[];counts:{total:number;announced:number;unannounced:number}};
const LABEL:Record<Status,string>={ENTERING_DRAFT:"Entering NFL Draft",RETURNING_TO_SCHOOL:"Returning to School",TRANSFER_PORTAL:"Transfer Portal"};
const OPTIONS=(Object.keys(LABEL) as Status[]);

export default function DraftStatusModal({open,onClose,onDone}:{open:boolean;onClose:()=>void;onDone?:()=>void}){
 const draftClass=useDraftClass(),[tab,setTab]=useState<"search"|"manual"|"unannounced">("search"),[data,setData]=useState<Data|null>(null),[findings,setFindings]=useState<Finding[]>([]),[verified,setVerified]=useState<Set<string>>(new Set()),[busy,setBusy]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState(""),[progress,setProgress]=useState(""),[q,setQ]=useState("");
 const [playerId,setPlayerId]=useState(""),[status,setStatus]=useState<Status>("ENTERING_DRAFT"),[sourceUrl,setSourceUrl]=useState(""),[sourceTitle,setSourceTitle]=useState(""),[note,setNote]=useState("");
 async function load(){const r=await fetch(`/api/draft-status?draftClass=${draftClass}`,{cache:"no-store"}),j=await r.json();if(!r.ok)throw new Error(j?.error||"Could not load draft status.");setData(j)}
 useEffect(()=>{if(!open)return;setBusy(true);setError("");setMessage("");setFindings([]);setVerified(new Set());setTab("search");void load().catch(e=>setError(e?.message||"Could not load draft status.")).finally(()=>setBusy(false))},[open,draftClass]);
 const unannounced=data?.unannounced||[],players=data?.players||[];
 const filtered=useMemo(()=>unannounced.filter(p=>!q.trim()||(p.name+" "+p.position+" "+(p.college||"")).toLowerCase().includes(q.toLowerCase())),[unannounced,q]);
 async function searchWeb(){setBusy(true);setError("");setMessage("");setFindings([]);setVerified(new Set());try{const found:Finding[]=[];for(let i=0;i<unannounced.length;i+=8){const batch=unannounced.slice(i,i+8);setProgress(`Searching reliable sources… ${Math.min(i+batch.length,unannounced.length)} / ${unannounced.length}`);const r=await fetch("/api/draft-status/search",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({draftClass,playerIds:batch.map(p=>p.playerId)})}),j=await r.json();if(!r.ok)throw new Error(j?.error||"Search failed.");if(Array.isArray(j?.findings))found.push(...j.findings)}setFindings([...new Map(found.map(f=>[String(f.playerId),f])).values()]);setMessage(found.length?`Found ${found.length} possible announcement${found.length===1?"":"s"}. Verify the source before applying.`:"No qualifying announcements were found from the approved sources.")}catch(e:any){setError(e?.message||"Search failed.")}finally{setProgress("");setBusy(false)}}
 async function apply(payload:any){const r=await fetch("/api/draft-status",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)}),j=await r.json();if(!r.ok)throw new Error(j?.error||"Could not apply status.");return j}
 async function applyVerified(){const selected=findings.filter(f=>verified.has(String(f.playerId)));if(!selected.length)return setError("Verify at least one source first.");setBusy(true);setError("");try{let n=0;for(const f of selected){setProgress(`Applying… ${n+1} / ${selected.length}`);await apply({playerId:f.playerId,draftClass,status:f.status,sourceUrl:f.sourceUrl,sourceTitle:f.sourceTitle,sourceType:f.sourceType,announcementDate:f.announcementDate,note:f.evidence,setMethod:"WEB"});n++}setMessage(`${n} verified decision${n===1?"":"s"} applied.`);setFindings(v=>v.filter(f=>!verified.has(String(f.playerId))));setVerified(new Set());await load();window.dispatchEvent(new Event("rookie-draft:players-changed"));onDone?.()}catch(e:any){setError(e?.message||"Could not apply decisions.");await load().catch(()=>{})}finally{setProgress("");setBusy(false)}}
 async function applyManual(){if(!playerId)return setError("Select a player.");setBusy(true);setError("");try{const p=players.find(x=>String(x.playerId)===playerId);await apply({playerId,draftClass,status,sourceUrl:sourceUrl.trim()||null,sourceTitle:sourceTitle.trim()||null,note:note.trim()||null,setMethod:"MANUAL"});setMessage(`${p?.name||"Player"}: ${LABEL[status]} applied.`);setPlayerId("");setSourceUrl("");setSourceTitle("");setNote("");await load();window.dispatchEvent(new Event("rookie-draft:players-changed"));onDone?.()}catch(e:any){setError(e?.message||"Could not apply status.");await load().catch(()=>{})}finally{setBusy(false)}}
 function toggle(id:string){setVerified(v=>{const n=new Set(v);n.has(id)?n.delete(id):n.add(id);return n})}
 if(!open)return null;
 return <div className="tool-modal-backdrop" role="dialog" aria-modal="true" onMouseDown={e=>e.target===e.currentTarget&&!busy&&onClose()}><div className="tool-modal" style={{width:"min(920px,96vw)",maxHeight:"90vh",overflow:"auto"}} onMouseDown={e=>e.stopPropagation()}>
  <div className="page-head"><div><div className="ey">GM Tools · {draftClass}</div><h2>Draft Status Check</h2><p className="muted">Search, verify, and apply NFL Draft decisions. Nothing found on the web changes a player until you approve the source.</p></div><button className="small ghost" disabled={busy} onClick={onClose}>Close</button></div>
  <div className="grid" style={{gridTemplateColumns:"repeat(3,1fr)",marginBottom:12}}><div className="notice"><b>{data?.counts.announced??0}/{data?.counts.total??0}</b><br/><span className="muted">decisions recorded</span></div><div className="notice"><b>{data?.counts.unannounced??0}</b><br/><span className="muted">unannounced</span></div><div className="notice"><b>Manual approval</b><br/><span className="muted">required for web results</span></div></div>
  <div className="row-actions" style={{marginBottom:14}}><button className={tab==="search"?"":"ghost"} onClick={()=>setTab("search")}>Web Search</button><button className={tab==="manual"?"":"ghost"} onClick={()=>setTab("manual")}>Manual</button><button className={tab==="unannounced"?"":"ghost"} onClick={()=>setTab("unannounced")}>Unannounced ({unannounced.length})</button></div>
  {tab==="search"&&<div><div className="notice"><b>Reliable-source filter:</b> ESPN, CBS Sports, NBC Sports, player-owned social accounts, or clearly credentialed/verified reporter or official social accounts. Rumors, mock drafts, aggregators and projections are ignored.</div><button disabled={busy||!unannounced.length} onClick={searchWeb}>{busy?"Searching…":`Search ${unannounced.length} Unannounced Players`}</button>{progress&&<p className="muted">{progress}</p>}
   <div style={{display:"grid",gap:10,marginTop:12}}>{findings.map(f=><div className="notice" key={f.playerId}><div style={{display:"flex",justifyContent:"space-between",gap:12,flexWrap:"wrap"}}><div><div className="ey">{LABEL[f.status]}</div><b>{f.playerName}</b>{f.announcementDate&&<span className="muted"> · {f.announcementDate}</span>}</div><a className="historical-source-link" href={f.sourceUrl} target="_blank" rel="noreferrer">Open source ↗</a></div>{f.evidence&&<p className="muted">{f.evidence}</p>}<div className="muted" style={{fontSize:11,overflowWrap:"anywhere"}}>{f.sourceTitle||f.sourceUrl}</div><label style={{display:"flex",gap:8,alignItems:"center",marginTop:9}}><input type="checkbox" checked={verified.has(String(f.playerId))} onChange={()=>toggle(String(f.playerId))}/> I verified this source</label></div>)}</div>{findings.length>0&&<button className="success" style={{marginTop:12}} disabled={busy||!verified.size} onClick={applyVerified}>Apply {verified.size} Verified Decision{verified.size===1?"":"s"}</button>}
  </div>}
  {tab==="manual"&&<div className="grid"><label>Player<select value={playerId} onChange={e=>setPlayerId(e.target.value)}><option value="">Select player…</option>{players.map(p=><option key={p.playerId} value={p.playerId}>{p.position} · {p.name} · {p.college||"College TBD"}{p.status?` · ${LABEL[p.status]}`:" · Unannounced"}</option>)}</select></label><label>Decision<select value={status} onChange={e=>setStatus(e.target.value as Status)}>{OPTIONS.map(v=><option value={v} key={v}>{LABEL[v]}</option>)}</select></label><label>Source URL (optional)<input value={sourceUrl} onChange={e=>setSourceUrl(e.target.value)} placeholder="https://…"/></label><label>Source title (optional)<input value={sourceTitle} onChange={e=>setSourceTitle(e.target.value)} placeholder="Player post / ESPN report…"/></label><label style={{gridColumn:"1/-1"}}>Note (optional)<textarea rows={3} value={note} onChange={e=>setNote(e.target.value)} /></label><button className="success" disabled={busy||!playerId} onClick={applyManual}>Apply Manual Decision</button></div>}
  {tab==="unannounced"&&<div><div className="toolbar"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search unannounced players…"/><span className="muted">{filtered.length} without a {draftClass} decision</span></div><table style={{width:"100%"}}><thead><tr><th>Pos</th><th>Player</th><th>College</th><th>Status</th></tr></thead><tbody>{filtered.map(p=><tr key={p.playerId}><td>{p.position}</td><td><b>{p.name}</b></td><td>{p.college||"—"}</td><td>Unannounced</td></tr>)}</tbody></table>{!filtered.length&&<div className="empty">No matching unannounced players.</div>}</div>}
  {error&&<div className="notice" style={{marginTop:12,borderColor:"#7b3340"}}>{error}</div>}{message&&<div className="notice" style={{marginTop:12,borderColor:"#2b7652"}}>{message}</div>}
 </div></div>;
}
