"use client";
import {useEffect,useState} from "react";
import {MOCK_POSITIONS,bestCpuPick,tendencyFor,type MockLeagueRoom,type MockPosition,type SimulatedPick} from "@/lib/mock-draft";
type P={open:boolean;draftClass:number;onClose:()=>void};
const openSlot=(r:MockLeagueRoom,p:SimulatedPick[])=>{const x=new Set(p.map(v=>v.pickNo));return r.slots.find(v=>!v.livePlayer&&!x.has(v.pickNo))||null};
const available=(r:MockLeagueRoom,p:SimulatedPick[])=>{const ids=new Set(p.map(v=>v.candidate.id));return r.candidates.filter(v=>!ids.has(v.id)&&!r.slots.some(s=>s.livePlayer&&String(s.livePlayer).toLowerCase()===v.name.toLowerCase()))};
function run(r:MockLeagueRoom,start:SimulatedPick[],mine:number|null){const p=[...start];while(true){const s=openSlot(r,p);if(!s||s.rosterId===mine)return p;const t=r.teams.find(x=>x.rosterId===s.rosterId);if(!t)return p;const c:Partial<Record<MockPosition,number>>={};for(const z of p.filter(x=>x.rosterId===t.rosterId))c[z.candidate.position]=(c[z.candidate.position]||0)+1;const hit=bestCpuPick(available(r,p),t,s.pickNo,tendencyFor(t,r.tendencies),c,{superflex:r.league.superflex,tePremium:r.league.tePremium});if(!hit)return p;p.push({pickNo:s.pickNo,rosterId:s.rosterId,team:s.team,candidate:hit.candidate,byUser:false,rationale:hit.rationale})}}
export default function MockDraftModal({open,draftClass,onClose}:P){
 const [leagues,setLeagues]=useState<any[]>([]),[key,setKey]=useState(""),[room,setRoom]=useState<MockLeagueRoom|null>(null),[picks,setPicks]=useState<SimulatedPick[]>([]),[mine,setMine]=useState<number|null>(null),[selected,setSelected]=useState(""),[msg,setMsg]=useState("");
 useEffect(()=>{if(open)fetch("/api/mock-draft",{cache:"no-store"}).then(r=>r.json()).then(j=>{setLeagues(j.leagues||[]);setKey(j.leagues?.[0]?.key||"")})},[open]);
 if(!open)return null;const slot=room?openSlot(room,picks):null,team=room&&slot?room.teams.find(t=>t.rosterId===slot.rosterId):null,pool=room?available(room,picks):[],candidate=room?.candidates.find(c=>c.id===selected),turn=!!slot&&slot.rosterId===mine;
 async function launch(){const x=await fetch(`/api/mock-draft?leagueKey=${encodeURIComponent(key)}&draftClass=${draftClass}`,{cache:"no-store"}),j=await x.json();if(!x.ok)return setMsg(j.error||"Could not load draft.");const m=j.teams.find((t:any)=>t.isMine)?.rosterId??j.teams[0]?.rosterId??null;setRoom(j);setMine(m);setPicks(run(j,[],m))}
 async function history(f:File){const text=await f.text(),rows=f.name.endsWith(".json")?JSON.parse(text):(()=>{const a=text.trim().split(/\r?\n/),h=(a.shift()||"").split(",");return a.map(l=>Object.fromEntries(l.split(",").map((v,i)=>[h[i],v])))})();const x=await fetch("/api/mock-draft",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"import-history",leagueKey:key,sourceLabel:f.name,rows})}),j=await x.json();setMsg(x.ok?`Learned from ${j.samples||j.imported||0} historical picks.`:j.error)}
 function pick(){if(!room||!slot||!candidate||!turn)return;const next=[...picks,{pickNo:slot.pickNo,rosterId:slot.rosterId,team:slot.team,candidate,byUser:true,rationale:"Your selection."}];setPicks(run(room,next,mine));setSelected("")}
 return <div className="tool-modal-backdrop" style={{zIndex:120}}><div className="tool-modal" style={{width:"min(1100px,94vw)",maxWidth:"none",height:"min(760px,90vh)",display:"flex",flexDirection:"column",overflow:"hidden"}}>
  <div className="page-head"><div><div className="ey">GM Tools · Mock environment</div><h2>Mock Draft Simulator</h2></div><button className="small ghost" onClick={onClose}>Close</button></div>
  {!room?<div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:16,padding:8}}><div className="card"><h3>Choose league</h3><p className="muted">Resumes from the first open pick, keeps live selections locked, and uses the league-specific draft board.</p><select value={key} onChange={e=>setKey(e.target.value)} style={{width:"100%"}}>{leagues.map(l=><option key={l.key} value={l.key}>{l.name}</option>)}</select><button onClick={launch} style={{width:"100%",marginTop:12}}>Initialize Simulator</button></div><div className="card"><h3>Manager tendencies</h3><p className="muted">Upload prior draft CSV/JSON. Owner, player and position are enough; pick and board rank improve the profile.</p><label className="notice" style={{display:"block",textAlign:"center",cursor:"pointer"}}>Upload History<input type="file" accept=".csv,.json" hidden onChange={e=>{const f=e.target.files?.[0];if(f)void history(f)}}/></label>{msg&&<div className="notice">{msg}</div>}</div></div>:
  <div style={{display:"grid",gridTemplateColumns:"270px 1fr 300px",gap:10,minHeight:0,flex:1}}>
   <div style={{overflow:"auto"}}><div className="ey">Draft timeline</div>{room.slots.map(s=>{const sim=picks.find(p=>p.pickNo===s.pickNo);return <div key={s.pickNo} className="notice" style={{margin:"5px 0",padding:8,background:slot?.pickNo===s.pickNo?"#102846":undefined}}><b>{s.round}.{s.slot} · {s.team}</b><div className="muted">{s.livePlayer||sim?.candidate.name||"On the clock"}</div></div>})}</div>
   <div style={{overflow:"auto"}}><div className="ey">League board</div>{pool.slice(0,80).map(c=><button key={c.id} className="ghost" onClick={()=>setSelected(c.id)} style={{width:"100%",display:"flex",justifyContent:"space-between",margin:"4px 0",borderColor:selected===c.id?"#4f7fb6":undefined}}><span>#{c.rank} <b>{c.name}</b><small className="muted"> · {c.position} · {c.college}</small></span><span>{c.grade?.toFixed(1)||""}</span></button>)}</div>
   <div style={{overflow:"auto"}}>{!slot?<div className="card"><h3>Mock complete</h3><p className="muted">Nothing was written back to the live league.</p></div>:team?<><div className="card"><div className="ey">{turn?"You are on the clock":"CPU team"}</div><h3>{team.name}</h3><div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:5}}>{MOCK_POSITIONS.map(p=><div key={p} className="notice" style={{padding:5,textAlign:"center"}}><b>{p}</b><small style={{display:"block"}}>#{team.needs[p].rank} · {team.needs[p].label}</small></div>)}</div></div><div className="card" style={{marginTop:10}}><div className="ey">Manager profile</div><p className="muted">{(()=>{const t=tendencyFor(team,room.tendencies);return t?`${t.sampleSize} historical picks. QB ${Math.round(t.positionShare.QB*100)}% · RB ${Math.round(t.positionShare.RB*100)}% · WR ${Math.round(t.positionShare.WR*100)}% · TE ${Math.round(t.positionShare.TE*100)}%`:"No history imported yet; CPU uses roster need and board value."})()}</p></div><div className="card" style={{marginTop:10}}><h3>{candidate?.name||"Select a prospect"}</h3>{candidate&&<button disabled={!turn} onClick={pick} style={{width:"100%"}}>Draft {candidate.name}</button>}</div></>:null}</div>
  </div>}
 </div></div>
}