"use client";
import {createContext,useContext,useEffect,useState} from "react";
type Ctx={openPlayer:(id:string|number)=>void};const C=createContext<Ctx>({openPlayer:()=>{}});
const fmt=(x:any)=>x==null||!Number.isFinite(Number(x))?"—":Number(x).toFixed(2);
export function usePlayerProfile(){return useContext(C)}
export function PlayerProfileProvider({children}:{children:React.ReactNode}){const [id,setId]=useState<string|null>(null),[data,setData]=useState<any>(null),[tab,setTab]=useState("Summary"),[loading,setLoading]=useState(false);const openPlayer=(x:string|number)=>{setId(String(x));setTab("Summary")};useEffect(()=>{if(!id)return;setLoading(true);setData(null);fetch("/api/player-profile?id="+id,{cache:"no-store"}).then(r=>r.json()).then(setData).finally(()=>setLoading(false))},[id]);return <C.Provider value={{openPlayer}}>{children}{id&&<div className="player-profile-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setId(null)}><div className="player-profile-modal"><button className="player-profile-close" onClick={()=>setId(null)}>×</button>{loading?<div className="empty">Loading player profile…</div>:data?.player?<Profile d={data} tab={tab} setTab={setTab} open={openPlayer}/>:<div className="empty">Could not load player profile.</div>}</div></div>}</C.Provider>}
function Profile({d,tab,setTab,open}:{d:any,tab:string,setTab:(x:string)=>void,open:(id:any)=>void}){const p=d.player,g=d.grades,m=d.evaluations||[],img=p.headshot_url;return <><div className="player-profile-hero"><div className="profile-photo-wrap">{img?<img src={img} className="profile-photo" alt=""/>:<div className="profile-photo profile-photo-fallback">{p.name.split(" ").map((x:string)=>x[0]).slice(0,2).join("")}</div>}</div><div><div className="ey">{p.position} · {p.college}{p.jersey_number?" · #"+p.jersey_number:""}</div><h1>{p.name}</h1><div className="muted">2027 Prospect</div></div><div className="profile-final"><span>Final Grade</span><strong>{fmt(g.final)}</strong></div></div><div className="profile-tabs">{["Summary","Grades","Stats","Team"].map(x=><button className={tab===x?"active":""} onClick={()=>setTab(x)} key={x}>{x}</button>)}</div>{tab==="Summary"&&<Summary d={d}/>} {tab==="Grades"&&<Grades d={d}/>} {tab==="Stats"&&<Stats d={d}/>} {tab==="Team"&&<Team d={d} open={open}/>}</>}
function Summary({d}:{d:any}){const g=d.grades,p=d.player;return <div className="profile-pane"><h2>Grades</h2><div className="profile-grade-grid"><Grade label="Final Grade" value={g.final}/><Grade label="Scouting Grade" value={g.scouting}/>{p.position!=="QB"&&<Grade label="Production Grade" value={g.production}/>}<Grade label="Analytical Grade" value={g.analytical}/></div><div className="profile-two"><section><h2>NFL Draft Result</h2><p>{g.values["Draft Result"]||"Not drafted yet"}</p></section><section><h2>AI Summary of Notes</h2><p>{d.notesSummary}</p></section></div></div>}
function Grade({label,value}:{label:string,value:any}){const n=Number(value),pct=Number.isFinite(n)?Math.max(0,Math.min(100,n)):0;return <div className="profile-grade"><span>{label}</span><strong>{fmt(value)}</strong><div className="grade-track"><i style={{width:pct+"%"}}/></div></div>}
function Grades({d}:{d:any}){const g=d.grades,p=d.player,skip=new Set(["__COMMENTARY__","Draft Result"]);return <div className="profile-pane"><div className="profile-grade-grid"><Grade label="Final Grade" value={g.final}/><Grade label="Scouting Grade" value={g.scouting}/>{p.position!=="QB"&&<Grade label="Production Grade" value={g.production}/>}<Grade label="Analytical Grade" value={g.analytical}/></div><h2>Detailed Grades</h2><div className="detail-grades">{d.evaluations.filter((e:any)=>!skip.has(e.category)&&(e.value!=null||e.commentary)).map((e:any)=><div key={e.category}><span>{e.category}</span><b>{e.value??e.commentary}</b></div>)}</div></div>}
function Stats({d}:{d:any}){const s=d.stats;return <div className="profile-pane"><h2>ESPN Career Stats</h2>{s&&Object.keys(s).length?<pre className="stats-json">{JSON.stringify(s,null,2)}</pre>:<div className="empty">ESPN career statistics are not available for this player yet.</div>}</div>}
function Team({d,open}:{d:any,open:(id:any)=>void}){return <div className="profile-pane"><h2>{d.player.college} · Draft Eligible Players</h2><div className="team-prospects">{d.teamPlayers.map((x:any)=><button key={x.id} onClick={()=>open(x.id)}><b>{x.position}</b><span>{x.name}</span></button>)}</div><h2>Team Schedule & Results</h2><div className="profile-schedule">{d.schedule.map((e:any)=><div key={e.id}><span>{new Date(e.date).toLocaleDateString([],{month:"short",day:"numeric"})}</span><b>{e.shortName||e.name}</b><span>{e.status}</span></div>)}</div></div>}
