import {workbookReference as w} from "@/lib/workbook-reference";
import {currentCollegeStatsGeneratedAt,currentCollegeStatsReference} from "@/lib/current-college-stats-reference";
import {ensureTursoSchema,rows as resultRows} from "@/lib/turso";
function num(v:unknown){if(v===null||v===undefined||v==="")return null;const n=Number(String(v).replace(/,/g,""));return Number.isFinite(n)?n:null}
const LIVE_STAT_FIELDS=["games","completions","passAttempts","passYards","passYardsPerAttempt","passYardsPerCompletion","passTDs","passInterceptions","rushes","rushYards","yardsPerRush","rushTDs","totalPlays"] as const;
const SACRAMENTO_STATE_2026={games:5,completions:108,passAttempts:189,passYards:1081,passYardsPerAttempt:5.72,passYardsPerCompletion:10.01,passTDs:5,passInterceptions:6,rushes:152,rushYards:556,yardsPerRush:3.66,rushTDs:4,totalPlays:341,updatedAt:"2026-10-05T00:00:00.000Z"};
function cleanPlayers(v:any){return typeof v==="string"?v.replace(/\bNIck Minicucci\b/g,"Nick Minicucci"):v}
function statSignature(r:any){return LIVE_STAT_FIELDS.map(k=>r?.[k]??"").join("|")}
function sanitize(rs:any[]){const out=rs.map(r=>({...r,players:cleanPlayers(r.players)})),ndsu=out.find(r=>r.team==="North Dakota State"),sac=out.find(r=>r.team==="Sacramento State");if(ndsu&&sac&&statSignature(ndsu)&&statSignature(ndsu)===statSignature(sac))for(const k of LIVE_STAT_FIELDS)sac[k]=null;return out}
function seedRows(rs:any[],subdivision:"FBS"|"FCS"){return rs.slice(2).filter(r=>r?.[1]).map(r=>({team:String(r[1]),subdivision,rank:num(r[0]),playersToScout:num(r[2]),players:cleanPlayers(r[3]??null),games:num(r[4]),completions:num(r[5]),passAttempts:num(r[6]),passYards:num(r[7]),passYardsPerAttempt:num(r[8]),passYardsPerCompletion:num(r[9]),passTDs:num(r[10]),passInterceptions:num(r[11]),rushes:num(r[14]),rushYards:num(r[15]),yardsPerRush:num(r[16]),rushTDs:num(r[17]),totalPlays:num(r[21]),yac:num(r[25]),airYards:num(r[26])}))}
const select="select team,subdivision,rank,players_to_scout as playersToScout,players,games,completions,pass_attempts as passAttempts,pass_yards as passYards,pass_yards_per_attempt as passYardsPerAttempt,pass_yards_per_completion as passYardsPerCompletion,pass_tds as passTDs,pass_interceptions as passInterceptions,rushes,rush_yards as rushYards,yards_per_rush as yardsPerRush,rush_tds as rushTDs,total_plays as totalPlays,yac,air_yards as airYards,updated_at as updatedAt from college_stats order by subdivision,team";
async function save(rs:any[],timestamp?:string){const q=await ensureTursoSchema(),now=timestamp||new Date().toISOString();for(const r of rs){if(!r?.team)continue;await q.execute({sql:"insert into college_stats(team,subdivision,rank,players_to_scout,players,games,completions,pass_attempts,pass_yards,pass_yards_per_attempt,pass_yards_per_completion,pass_tds,pass_interceptions,rushes,rush_yards,yards_per_rush,rush_tds,total_plays,yac,air_yards,updated_at) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) on conflict(team) do update set subdivision=excluded.subdivision,rank=excluded.rank,players_to_scout=excluded.players_to_scout,players=excluded.players,games=excluded.games,completions=excluded.completions,pass_attempts=excluded.pass_attempts,pass_yards=excluded.pass_yards,pass_yards_per_attempt=excluded.pass_yards_per_attempt,pass_yards_per_completion=excluded.pass_yards_per_completion,pass_tds=excluded.pass_tds,pass_interceptions=excluded.pass_interceptions,rushes=excluded.rushes,rush_yards=excluded.rush_yards,yards_per_rush=excluded.yards_per_rush,rush_tds=excluded.rush_tds,total_plays=excluded.total_plays,yac=excluded.yac,air_yards=excluded.air_yards,updated_at=excluded.updated_at",args:[r.team,r.subdivision==="FCS"?"FCS":"FBS",r.rank??null,r.playersToScout??null,cleanPlayers(r.players??null),r.games??null,r.completions??null,r.passAttempts??null,r.passYards??null,r.passYardsPerAttempt??null,r.passYardsPerCompletion??null,r.passTDs??null,r.passInterceptions??null,r.rushes??null,r.rushYards??null,r.yardsPerRush??null,r.rushTDs??null,r.totalPlays??null,r.yac??null,r.airYards??null,now]})}}
export async function GET(){try{const q=await ensureTursoSchema();let rs=resultRows(await q.execute(select));const sacramento=rs.find((r:any)=>r.team==="Sacramento State");if(!sacramento||Number(sacramento.games)!==SACRAMENTO_STATE_2026.games||Number(sacramento.passYards)!==SACRAMENTO_STATE_2026.passYards||Number(sacramento.rushYards)!==SACRAMENTO_STATE_2026.rushYards){await save([{...(sacramento||{}),team:"Sacramento State",subdivision:sacramento?.subdivision||"FBS",rank:sacramento?.rank??124,playersToScout:sacramento?.playersToScout??0,players:cleanPlayers(sacramento?.players??"None"),...SACRAMENTO_STATE_2026}],SACRAMENTO_STATE_2026.updatedAt);rs=resultRows(await q.execute(select))}const newest=rs.reduce((m:any,r:any)=>!m||String(r.updatedAt||"")>String(m)?r.updatedAt:m,null);if(!rs.length||!newest||String(newest)<currentCollegeStatsGeneratedAt){await save(currentCollegeStatsReference as unknown as any[],currentCollegeStatsGeneratedAt);rs=resultRows(await q.execute(select))}if(!rs.length){await save([...seedRows(w.colleges as any[],"FBS"),...seedRows(w.nonFbs as any[],"FCS")]);rs=resultRows(await q.execute(select))}return Response.json(sanitize(rs))}catch(e:unknown){return Response.json({error:e instanceof Error?e.message:"Could not load college stats"},{status:500})}}
export async function POST(req:Request){try{const body=await req.json(),rs=Array.isArray(body)?body:body?.rows;if(!Array.isArray(rs)||!rs.length)return Response.json({error:"rows must be a non-empty array"},{status:400});await save(rs);return Response.json({ok:true,count:rs.length})}catch(e:unknown){return Response.json({error:e instanceof Error?e.message:"Could not save college stats"},{status:400})}}
