import {db,ensureSchema} from "@/lib/db";
const norm=(s:string)=>String(s||"").toLowerCase().replace(/&/g,"and").replace(/[^a-z0-9]+/g," ").trim().replace(/\s+/g," ");
const aliases:Record<string,string>={"miami fl":"miami florida","mizzou":"missouri","uconn":"connecticut","umass":"massachusetts","nc state":"north carolina state","usc":"southern california","ole miss":"mississippi","cal":"california","usf":"south florida","app state":"appalachian state","wku":"western kentucky"};
const key=(s:string)=>aliases[norm(s)]||norm(s);
function athletes(x:any,out:any[]=[]){if(!x||typeof x!=="object")return out;if((x.id||x.uid)&&(x.fullName||x.displayName||x.name)&&((x.position?.abbreviation)||x.jersey||x.headshot))out.push(x);if(Array.isArray(x))for(const v of x)athletes(v,out);else for(const v of Object.values(x))athletes(v,out);return out}
export async function GET(req:Request){try{await ensureSchema();const id=new URL(req.url).searchParams.get("id");if(!id)return Response.json({error:"Missing player id"},{status:400});const q=db(),[p]=await q`select * from players where id=${id}`;if(!p)return Response.json({error:"Player not found"},{status:404});if(p.headshot_url)return Response.json({url:p.headshot_url,espnId:p.espn_athlete_id,source:p.headshot_source||"ESPN",cached:true});
 const rows=await q`select event from college_football_events order by kickoff desc`;let teamId="";for(const r of rows){for(const comp of r.event?.competitions?.[0]?.competitors||[]){const t=comp.team||{},names=[t.location,t.displayName,t.shortDisplayName,t.name,t.abbreviation].filter(Boolean);if(names.some((n:string)=>key(n)===key(p.college))){teamId=String(t.id||"");break}}if(teamId)break}
 if(!teamId)return Response.json({url:null,reason:"team-not-found"});
 const rr=await fetch(`https://site.api.espn.com/apis/site/v2/sports/football/college-football/teams/${teamId}/roster`,{next:{revalidate:86400}});if(!rr.ok)return Response.json({url:null,reason:"espn-roster-"+rr.status});const data=await rr.json(),all=athletes(data),target=key(p.name);const a=all.find((x:any)=>[x.fullName,x.displayName,x.name].filter(Boolean).some((n:string)=>key(n)===target));if(!a)return Response.json({url:null,reason:"player-not-found"});
 const espnId=String(a.id||"").replace(/^s:.*?~a:/,""),url=a.headshot?.href||a.headshot||`https://a.espncdn.com/i/headshots/college-football/players/full/${espnId}.png`;await q`update players set espn_athlete_id=${espnId},headshot_url=${url},headshot_source='ESPN',updated_at=now() where id=${p.id}`;return Response.json({url,espnId,source:"ESPN",cached:false})
 }catch(e:any){return Response.json({error:"Could not resolve headshot",detail:e?.message},{status:500})}}
