"use client";
import {FormEvent,useEffect,useState} from "react";
import {ShieldCheck,ShieldX} from "lucide-react";
export default function AdminPage(){
  const [authenticated,setAuthenticated]=useState(false),[configured,setConfigured]=useState(true),[password,setPassword]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
  const check=()=>fetch("/api/auth/status",{cache:"no-store"}).then(r=>r.json()).then(j=>{setAuthenticated(Boolean(j.authenticated));setConfigured(j.configured!==false)}).catch(()=>{});
  useEffect(()=>{void check()},[]);
  async function login(e:FormEvent){e.preventDefault();setBusy(true);setMessage("");try{const r=await fetch("/api/auth/login",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({password})}),j=await r.json();if(!r.ok)throw new Error(j.error||"Sign-in failed");setPassword("");setMessage("Admin session unlocked.");await check();window.dispatchEvent(new Event("rookie-draft:auth-changed"))}catch(e:any){setMessage(e?.message||"Sign-in failed")}finally{setBusy(false)}}
  async function logout(){setBusy(true);await fetch("/api/auth/logout",{method:"POST"});setAuthenticated(false);setMessage("Admin session locked.");setBusy(false);window.dispatchEvent(new Event("rookie-draft:auth-changed"))}
  return <div className="admin-page"><div className="page-head"><div><div className="ey">Security</div><h1>Admin Access</h1><p className="muted">Reading remains available without a login. Changes, imports, refreshes and server exports require this admin session.</p></div></div><div className="card admin-card"><div className={"admin-shield "+(authenticated?"unlocked":"locked")}>{authenticated?<ShieldCheck size={34}/>:<ShieldX size={34}/>}</div><div><span className="ey">Write access</span><h2>{authenticated?"Unlocked on this browser":"Locked"}</h2><p className="muted">{authenticated?"Your secure session cookie keeps write access active for up to 30 days.":"Sign in once on each browser you use for scouting."}</p></div>{authenticated?<button className="ghost" disabled={busy} onClick={logout}>Lock admin session</button>:<form onSubmit={login}><input type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Admin password" disabled={!configured||busy}/><button className="success" disabled={!configured||busy||!password}>{busy?"Signing in…":"Unlock write access"}</button></form>}{!configured&&<div className="notice">Admin authentication has not been configured in the deployment environment.</div>}{message&&<div className="notice">{message}</div>}</div></div>
}
