import {ensureTursoSchema,rows} from "@/lib/turso";
const ALLOWED=new Set(["QB","RB","WR","TE"]);
const TEAM_ALIASES:Record<string,string>={"SF":"49ers","SAN FRANCISCO 49ERS":"49ers","CHI":"Bears","CHICAGO BEARS":"Bears","CIN":"Bengals","CINCINNATI BENGALS":"Bengals","BUF":"Bills","BUFFALO BILLS":"Bills","DEN":"Broncos","DENVER BRONCOS":"Broncos","CLE":"Browns","CLEVELAND BROWNS":"Browns","TB":"Buccaneers","TAMPA BAY BUCCANEERS":"Buccaneers","ARI":"Cardinals","ARIZONA CARDINALS":"Cardinals","LAC":"Chargers","LOS ANGELES CHARGERS":"Chargers","KC":"Chiefs","KANSAS CITY CHIEFS":"Chiefs","IND":"Colts","INDIANAPOLIS COLTS":"Colts","WAS":"Commanders","WSH":"Commanders","WASHINGTON COMMANDERS":"Commanders","DAL":"Cowboys","DALLAS COWBOYS":"Cowboys","MIA":"Dolphins","MIAMI DOLPHINS":"Dolphins","PHI":"Eagles","PHILADELPHIA EAGLES":"Eagles","ATL":"Falcons","ATLANTA FALCONS":"Falcons","NYG":"Giants","NEW YORK GIANTS":"Giants","JAX":"Jaguars","JACKSONVILLE JAGUARS":"Jaguars","NYJ":"Jets","NEW YORK JETS":"Jets","DET":"Lions","DETROIT LIONS":"Lions","GB":"Packers","GREEN BAY PACKERS":"Packers","CAR":"Panthers","CAROLINA PANTHERS":"Panthers","NE":"Patriots","NEW ENGLAND PATRIOTS":"Patriots","LV":"Raiders","LAS VEGAS RAIDERS":"Raiders","LAR":"Rams","LOS ANGELES RAMS":"Rams","BAL":"Ravens","BALTIMORE RAVENS":"Ravens","NO":"Saints","NEW ORLEANS SAINTS":"Saints","SEA":"Seahawks","SEATTLE SEAHAWKS":"Seahawks","PIT":"Steelers","PITTSBURGH STEELERS":"Steelers","HOU":"Texans","HST":"Texans","HOUSTON TEXANS":"Texans","TEN":"Titans","TENNESSEE TITANS":"Titans","MIN":"Vikings","MINNESOTA VIKINGS":"Vikings"};
type Pick={round:number;overall:number;selection:string;team:string;player:string;position:string;college:string};
const clean=(s:string)=>s.replace(/<[^>]*>/g,"").replace(/\[[^\]]*\]/g,"").replace(/&#160;|&nbsp;|&#42;|\*|×|†/g,"").replace(/&amp;/g,"&").replace(/&lt;/g,"<").replace(/&gt;/g,">").replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/\s+/g," ").trim();
const norm=(s:unknown)=>String(s||"").trim().toUpperCase();
function teamFrom(x:any){if(!x)return "";for(const v of [typeof x==="string"?x:null,x.abbreviation,x.shortDisplayName,x.displayName,x.name,x.location&&x.name?\`\${x.location} \${x.name}\`:null]){if(!v)continue;const hit=TEAM_ALIASES[norm(v)];if(hit)return hit}return typeof x==="string"?x:(x.displayName||x.name||"")}
function roundForOverall(n:number){if(n<=32)return 1;if(n<=64)return 2;if(n<=100)return 3;if(n<=135)return 4;if(n<=176)return 5;if(n<=220)return 6;return 7}
function first(...v:any[]){return v.find(x=>typeof x==="string"&&x.trim())||""}
function extractEspn(root:any){const out:Pick[]=[],seen=new Set<string>();function walk(node:any){if(Array.isArray(node)){node.forEach(walk);return}if(!node||typeof node!=="object")return;const a=node.athlete||node.player||node.person||node.pick?.person||node.selection?.athlete||node.draftPick?.athlete;const player=first(a?.displayName,a?.fullName,node.pick?.person?.displayName,node.pick?.athlete?.displayName,node.selection?.athlete?.displayName);const position=first(a?.position?.abbreviation,a?.position?.name,node.position?.abbreviation,typeof node.position==="string"?node.position:"",node.pos,node.pick?.position?.abbreviation).toUpperCase();const overall=Number(node.overallPick??node.overall??node.overallSelection??node.pickNumber??node.selectionNumber??node.pick?.overall??node.pick?.number);if(player&&overall>0&&ALLOWED.has(position)){const k=\`\${overall}|\${player.toLowerCase()}\`;if(!seen.has(k)){seen.add(k);const round=Number(node.round??node.draftRound??node.pick?.round)||roundForOverall(overall);out.push({round,overall,selection:\`\${round}.\${String(overall).padStart(2,"0")}\`,team:teamFrom(node.team||node.nflTeam||node.pick?.team||node.selection?.team),player,position,college:first(a?.college?.name,a?.college?.displayName,node.college?.name,typeof node.college==="string"?node.college:"")})}}Object.values(node).forEach(walk)}walk(root);return out.sort((a,b)=>a.overall-b.overall)}
function parseWikipedia(html:string){const out:Pick[]=[];for(const table of html.match(/<table[^>]*class="[^"]*wikitable[^"]*"[^>]*>[\s\S]*?<\/table>/g)||[]){if(!table.includes("Pick")&&!table.includes("Player"))continue;for(const row of table.match(/<tr[\s\S]*?<\/tr>/g)||[]){if(!row.includes("<td"))continue;const cells=(row.match(/<t[hd][^>]*>[\s\S]*?<\/t[hd]>/g)||[]).map(clean);if(cells.length<7)continue;const round=Number(cells[1]),overall=Number(cells[2].replace(/\s+/g,"")),team=teamFrom(cells[3]),player=cells[4],position=cells[5],college=cells[6]==="Missouri"?"Mizzou":cells[6];if(overall&&player&&ALLOWED.has(position))out.push({round,overall,selection:\`\${round}.\${String(overall).padStart(2,"0")}\`,team,player,position,college})}}return out}
async function fetchDraft(year:number){const settled=await Promise.allSettled(Array.from({length:7},(_,i)=>fetch(\`https://site.web.api.espn.com/apis/v2/scoreboard/header?draft_year=\${year}&draft_round=\${i+1}\`,{cache:"no-store",headers:{"user-agent":"RookieDraftWebApp/2.0"}}).then(async r=>{if(!r.ok)throw new Error(\`ESPN \${r.status}\`);return r.json()})));const payloads=settled.filter((x):x is PromiseFulfilledResult<any>=>x.status==="fulfilled").map(x=>x.value);let picks=[...new Map(payloads.flatMap(extractEspn).map(p=>[\`\${p.overall}|\${p.player.toLowerCase()}\`,p])).values()].sort((a,b)=>a.overall-b.overall);let source="ESPN";if(!picks.length){try{const r=await fetch(\`https://en.wikipedia.org/wiki/\${year}_NFL_draft\`,{cache:"no-store",headers:{"user-agent":"Mozilla/5.0 (compatible; RookieDraftWebApp/2.0)"}});if(r.ok){picks=parseWikipedia(await r.text());source="Wikipedia fallback"}}catch{}}return {picks,source}}
async function persist(year:number,picks:Pick[]){const q=await ensureTursoSchema(),now=new Date().toISOString();for(const p of picks){await q.execute({sql:"insert into nfl_draft_picks(year,selection,round,overall_pick,position,player,college,team,imported_at) values(?,?,?,?,?,?,?,?,?) on conflict(year,selection) do update set position=excluded.position,player=excluded.player,college=excluded.college,team=excluded.team,imported_at=excluded.imported_at",args:[year,p.selection,p.round,p.overall,p.position,p.player,p.college,p.team,now]});const matches=rows(await q.execute({sql:"select id from players where draft_class=? and lower(name)=lower(?)",args:[year,p.player]}));for(const m of matches)await q.execute({sql:"insert into workflow_tags(player_id,tag,detail,updated_at) values(?,'DRAFTED',?,?) on conflict(player_id,tag) do update set detail=excluded.detail,updated_at=excluded.updated_at",args:[m.id,p.selection,now]})}}
async function cached(year:number){const q=await ensureTursoSchema();return rows(await q.execute({sql:"select * from nfl_draft_picks where year=? order by overall_pick",args:[year]}))}
export async function GET(req:Request){try{const u=new URL(req.url),year=Number(u.searchParams.get("year")||2027),refresh=u.searchParams.get("refresh")==="1";let source="Turso cache",syncError="";if(refresh){try{const live=await fetchDraft(year);source=live.source;if(live.picks.length)await persist(year,live.picks)}catch(e:unknown){syncError=e instanceof Error?e.message:String(e)}}const picks=await cached(year),max=Math.max(0,...picks.map((p:any)=>Number(p.overall_pick)||0));return Response.json({picks,complete:max>=257,source,refreshedAt:new Date().toISOString(),syncError:syncError||undefined})}catch(e:unknown){return Response.json({error:e instanceof Error?e.message:"Draft results unavailable"},{status:500})}}
export async function POST(req:Request){try{const body=await req.json().catch(()=>({})),year=Number(body.year||2027);const live=await fetchDraft(year);if(live.picks.length)await persist(year,live.picks);const picks=await cached(year),max=Math.max(0,...picks.map((p:any)=>Number(p.overall_pick)||0));return Response.json({count:live.picks.length,picks,complete:max>=257,source:live.source})}catch(e:unknown){return Response.json({error:e instanceof Error?e.message:"NFL Draft sync failed"},{status:500})}}
