"use client";
import {ChangeEvent,useState} from "react";
const PREFIX="rookie-draft.";
export default function Page(){
 const [msg,setMsg]=useState(""),[backupMsg,setBackupMsg]=useState("");
 async function submit(e:any){e.preventDefault();setMsg("Processing…");try{const fd=new FormData(e.currentTarget);const r=await fetch('/api/pff-process',{method:'POST',body:fd});const j=await r.json();setMsg(r.ok?`Processed ${j.files} CSV files. ${j.summary}`:(j.error||"Processing failed"))}catch{setMsg("Could not reach the processor. Your source files were not changed.")}}
 function exportBackup(){const data:any={version:1,exportedAt:new Date().toISOString(),items:{}};for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(k?.startsWith(PREFIX))data.items[k]=localStorage.getItem(k)}const blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`rookie-draft-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href);setBackupMsg(`Backup created with ${Object.keys(data.items).length} app data sets.`)}
 async function importBackup(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];if(!file)return;try{const data=JSON.parse(await file.text());if(data?.version!==1||!data?.items||typeof data.items!=="object")throw 0;let n=0;for(const [k,v] of Object.entries(data.items)){if(k.startsWith(PREFIX)&&typeof v==="string"){localStorage.setItem(k,v);n++}}setBackupMsg(`Restored ${n} app data sets to this browser. Refresh pages to see restored data.`)}catch{setBackupMsg("That file is not a valid Rookie Draft backup. Nothing was changed.")}finally{e.target.value=""}}
 return <><h1>Data Center</h1><p className="muted">Imports, backups, and migration tools. Legacy Rookie Draft workbooks remain read-only reference sources.</p>
 <div className="card"><h2>Browser backup</h2><p className="muted">Until cloud persistence is connected, use this to protect Players to Scout, film commentary, Game Notes, and Post-Game Reviews stored on this device.</p><div className="row-actions"><button onClick={exportBackup}>Download app backup</button><label className="buttonlike ghost">Restore backup<input style={{display:"none"}} type="file" accept="application/json,.json" onChange={importBackup}/></label></div>{backupMsg&&<p>{backupMsg}</p>}</div>
 <form className="card" onSubmit={submit}><h2>PFF CSV Processor</h2><p className="muted">Upload PFF exports together. This integration is still being parity-checked against the original processor; processed output should be treated as migration preview data until that audit is complete.</p><input type="file" name="files" accept=".csv" multiple required/><div className="grid" style={{marginTop:14}}>{[['QB','QB - Minimum Dropbacks'],['RB','RB - Minimum Rush Attempts'],['WR','WR - Minimum Targets'],['TE','TE - Minimum Targets']].map(([p,label],i)=><label key={p}>{label}<input name={p} type="number" min="0" defaultValue={[100,50,30,20][i]}/></label>)}</div><button style={{marginTop:14}}>Process PFF Files</button><p>{msg}</p></form></>;
}